# Docker Compose file version
version: '3.8'

# Define the services (containers) for your application
services:
  
  # --- Database Service ---
  db:
    image: postgres:15-alpine 
    container_name: forson_db
    restart: always
    environment:
      # UPDATED: Using an environment variable for the password for better security.
      # Make sure to add DB_PASSWORD=your_password to your .env file in packages/api.
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: forson_business_suite
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    ports:
      - "5432:5432"

  # --- Backend API Service ---
  backend:
    container_name: forson_backend
    # REMOVED: The 'build' instruction is replaced by 'image'.
    # This tells Docker Compose to pull a pre-built image from Docker Hub.
    image: kentonel/forson-backend:latest 
    restart: always
    depends_on:
      - db 
    ports:
      - "3001:3001"
    env_file:
      - ./packages/api/.env 

  # --- Frontend Service ---
  frontend:
    container_name: forson_frontend
    # REMOVED: The 'build' instruction is replaced by 'image'.
    image: kentonel/forson-frontend:latest
    restart: always
    depends_on:
      - backend 
    ports:
      - "8080:80"

# Define a named volume to persist the PostgreSQL data
volumes:
  postgres_data:
