# Define the services (containers) for your application
services:
  
  # --- Database Service ---
  db:
    image: postgres:15-alpine 
    container_name: forson_db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: forson_business_suite
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    ports:
      - "5432:5432"

  # --- NEW: Meilisearch Service ---
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: forson_meilisearch
    restart: always
    environment:
      - MEILI_MASTER_KEY=${MEILISEARCH_MASTER_KEY}
    volumes:
      - meili_data:/meili_data
    ports:
      - "7700:7700"

  # --- Backend API Service ---
  backend:
    container_name: forson_backend
    image: kentonel/forson-backend:latest 
    restart: always
    depends_on:
      - db
      - meilisearch # Added dependency
    ports:
      - "3001:3001"
    env_file:
      - ./.env

  # --- Frontend Service ---
  frontend:
    container_name: forson_frontend
    image: kentonel/forson-frontend:latest
    restart: always
    depends_on:
      - backend 
    ports:
      - "8090:80"

  # --- Backup Service ---
  backup:
    image: postgres:15-alpine # Use the same postgres image for pg_dump
    container_name: forson_backup
    restart: always
    depends_on:
      - db
    volumes:
      - ./backups:/backups
      - ./backup:/docker-entrypoint-initdb.d
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - BACKUP_PATH=/backups
      - BACKUP_RETENTION_DAYS=${BACKUP_RETENTION_DAYS:-7}
    command: >
      bash -c "while true; do
        /docker-entrypoint-initdb.d/backup.sh;
        sleep 86400;
      done"

# Define a named volume to persist the PostgreSQL data and Meilisearch data
volumes:
  postgres_data:
  meili_data: