# Define the services (containers) for your application
services:
  
  # --- Database Service ---
  db:
    image: postgres:15-alpine 
    container_name: forson_db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: forson_business_suite
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    ports:
      - "5432:5432"

  # --- Backend API Service ---
  backend:
    container_name: forson_backend
    image: kentonel/forson-backend:latest 
    restart: always
    depends_on:
      - db 
    ports:
      - "3001:3001"
    env_file:
      - ./packages/api/.env.production 

  # --- Frontend Service ---
  frontend:
    container_name: forson_frontend
    image: kentonel/forson-frontend:latest
    restart: always
    depends_on:
      - backend 
    ports:
      - "8090:80"

# Define a named volume to persist the PostgreSQL data
volumes:
  postgres_data:
