import { useCallback, useEffect, useMemo, useState } from 'react';
import toast from 'react-hot-toast';
import api from '../api';
import Modal from '../components/ui/Modal';
import { useAuth } from '../contexts/AuthContext';

const CONFIG = {
    customer: { plural: 'customers', label: 'Customers', singular: 'customer', id: 'customer_id', permission: 'customers:edit' },
    supplier: { plural: 'suppliers', label: 'Suppliers', singular: 'supplier', id: 'supplier_id', permission: 'suppliers:edit' },
};

export default function PartyMergePage({ party, onNavigate }) {
    const cfg = CONFIG[party];
    const { hasPermission } = useAuth();
    const [items, setItems] = useState([]); const [suggestions, setSuggestions] = useState([]);
    const [selected, setSelected] = useState(new Set()); const [threshold, setThreshold] = useState('0.55');
    const [loading, setLoading] = useState(true); const [scanning, setScanning] = useState(false);
    const [dialog, setDialog] = useState(null); const [working, setWorking] = useState(false);
    const code = party === 'customer' ? 'customer_code' : 'supplier_code';

    const load = useCallback(async () => {
        setLoading(true);
        try {
            const [directory, queue] = await Promise.all([api.get(`/${cfg.plural}/merge-directory`), api.get(`/${cfg.plural}/duplicate-suggestions`)]);
            setItems(directory.data.items || []); setSuggestions(queue.data.suggestions || []); setSelected(new Set());
        } catch (error) { toast.error(error.response?.data?.message || `Could not load ${cfg.label.toLowerCase()}.`); }
        finally { setLoading(false); }
    }, [cfg.label, cfg.plural]);
    useEffect(() => { if (!hasPermission(cfg.permission)) { onNavigate(party === 'customer' ? 'customers' : 'suppliers'); return; } load(); }, [cfg.permission, hasPermission, load, onNavigate, party]);
    const selectedIds = useMemo(() => [...selected], [selected]);
    const preview = async (next) => {
        setDialog(next);
        try { const { data } = await api.post(`/${cfg.plural}/merge-preview`, { keepId: next.keepId, mergeIds: next.ids.filter(id => id !== next.keepId) }); setDialog(current => current?.ids.join() === next.ids.join() && current.keepId === next.keepId ? { ...current, preview: data } : current); }
        catch (error) { toast.error(error.response?.data?.message || 'Unable to preview merge.'); }
    };
    const openReview = (ids, suggestionIds = []) => { const unique = [...new Set(ids.map(Number))]; if (unique.length > 1) preview({ ids: unique, keepId: unique[0], suggestionIds, preview: null }); };
    const scan = async () => { setScanning(true); try { const { data } = await api.post(`/${cfg.plural}/scan-duplicates`, { threshold: Number(threshold) }); toast.success(`Scan complete: ${data.createdOrUpdated} candidate pair${data.createdOrUpdated === 1 ? '' : 's'} saved.`); await load(); } catch (error) { toast.error(error.response?.data?.message || 'Duplicate scan failed.'); } finally { setScanning(false); } };
    const merge = async () => { if (!dialog?.preview || dialog.preview.conflicts?.length) return; setWorking(true); try { const { data } = await api.post(`/${cfg.plural}/merge`, { keepId: dialog.keepId, mergeIds: dialog.ids.filter(id => id !== dialog.keepId), suggestionIds: dialog.suggestionIds, previewFingerprint: dialog.preview.previewFingerprint }); toast.success(`${data.result.mergedIds.length} ${cfg.singular}${data.result.mergedIds.length === 1 ? '' : 's'} merged.`); setDialog(null); await load(); } catch (error) { toast.error(error.response?.data?.message || 'Merge failed.'); } finally { setWorking(false); } };
    const dismiss = async id => { try { await api.post(`/${cfg.plural}/duplicate-suggestions/${id}/dismiss`); await load(); } catch (error) { toast.error(error.response?.data?.message || 'Unable to dismiss suggestion.'); } };
    const candidates = dialog?.ids.map(id => items.find(item => item[cfg.id] === id)).filter(Boolean) || [];
    const impact = dialog?.preview?.impact ? Object.values(dialog.preview.impact).reduce((sum, value) => sum + Number(value || 0), 0) : 0;

    return <div className="mx-auto max-w-6xl space-y-6 pb-8">
        <header className="rounded-2xl bg-gradient-to-br from-slate-950 via-slate-900 to-primary-950 px-6 py-7 text-white shadow-lg"><button type="button" onClick={() => onNavigate(party === 'customer' ? 'customers' : 'suppliers')} className="text-sm text-primary-200 hover:text-white">← Back to {cfg.label}</button><h1 className="mt-3 text-3xl font-bold">{cfg.label} duplicate cleanup</h1><p className="mt-2 max-w-3xl text-sm text-slate-300">Scan for possible duplicates, inspect their linked records, and explicitly choose the canonical {cfg.singular}. Saved drafts are rewritten and reconciled customer wallets are consolidated during a merge.</p></header>
        <section className="flex flex-wrap items-end justify-between gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-900"><div><h2 className="font-semibold text-slate-900 dark:text-white">Find possible duplicates</h2><p className="mt-1 text-sm text-slate-500">Local similarity produces candidates; Jev filters them when configured. Nothing merges automatically.</p></div><div className="flex items-end gap-3"><label className="text-xs font-medium uppercase tracking-wide text-slate-500">Similarity<input type="number" min="0.1" max="0.99" step="0.01" value={threshold} onChange={e => setThreshold(e.target.value)} className="mt-1 block w-24 rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-800" /></label><button type="button" onClick={scan} disabled={scanning} className="rounded-lg bg-primary-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{scanning ? 'Scanning…' : 'Scan for duplicates'}</button></div></section>
        <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-900"><div className="flex items-center justify-between border-b border-slate-200 p-5 dark:border-slate-700"><div><h2 className="font-semibold text-slate-900 dark:text-white">Directory</h2><p className="mt-1 text-sm text-slate-500">Select two or more records for a reviewed merge.</p></div><button type="button" disabled={selectedIds.length < 2} onClick={() => openReview(selectedIds)} className="rounded-lg bg-slate-900 px-3 py-2 text-sm font-semibold text-white disabled:opacity-40 dark:bg-primary-600">Merge selected {selectedIds.length > 1 ? `(${selectedIds.length})` : ''}</button></div>{loading ? <p className="p-10 text-center text-sm text-slate-500">Loading directory…</p> : <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500 dark:bg-slate-800"><tr><th className="p-4" /><th className="p-4">Name</th><th className="p-4">Code</th><th className="p-4 text-right">Linked records</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{items.map(item => <tr key={item[cfg.id]}><td className="p-4"><input aria-label={`Select ${item.display_name}`} type="checkbox" checked={selected.has(item[cfg.id])} onChange={() => setSelected(current => { const next = new Set(current); next.has(item[cfg.id]) ? next.delete(item[cfg.id]) : next.add(item[cfg.id]); return next; })} /></td><td className="p-4 font-medium text-slate-900 dark:text-white">{item.display_name}</td><td className="p-4 font-mono text-xs">{item[code]}</td><td className="p-4 text-right tabular-nums">{item.reference_count}</td></tr>)}</tbody></table></div>}</section>
        <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-900"><div className="border-b border-slate-200 p-5 dark:border-slate-700"><h2 className="font-semibold text-slate-900 dark:text-white">Review queue</h2><p className="mt-1 text-sm text-slate-500">{suggestions.length} pending suggestion{suggestions.length === 1 ? '' : 's'}.</p></div>{suggestions.length ? <div className="divide-y divide-slate-100 dark:divide-slate-800">{suggestions.map(s => <article key={s.suggestion_id} className="flex flex-wrap items-center justify-between gap-4 p-5"><div><p className="font-semibold text-slate-900 dark:text-white">{s.display_name} <span className="text-slate-400">↔</span> {s.duplicate_display_name}</p><p className="mt-1 text-sm text-slate-500">{Math.round(Number(s.confidence_score) * 100)}% match · {s.detection_method}</p></div><div className="flex gap-2"><button type="button" onClick={() => openReview([s[cfg.id], s[`duplicate_${cfg.id}`]], [s.suggestion_id])} className="rounded-lg bg-primary-600 px-3 py-2 text-sm font-semibold text-white">Review merge</button><button type="button" onClick={() => dismiss(s.suggestion_id)} className="rounded-lg border border-slate-300 px-3 py-2 text-sm dark:border-slate-700">Dismiss</button></div></article>)}</div> : <p className="p-10 text-center text-sm text-slate-500">No pending suggestions.</p>}</section>
        <Modal isOpen={Boolean(dialog)} onClose={() => !working && setDialog(null)} title={`Merge ${cfg.label}`} maxWidth="max-w-2xl"><div className="space-y-5">{candidates.map(candidate => <label key={candidate[cfg.id]} className="flex cursor-pointer items-center justify-between rounded-xl border p-4"><span><span className="block font-semibold">{candidate.display_name}</span><span className="text-xs text-slate-500">{candidate[code]}</span></span><input type="radio" checked={dialog?.keepId === candidate[cfg.id]} onChange={() => preview({ ...dialog, keepId: candidate[cfg.id], preview: null })} /></label>)}{dialog?.preview?.conflicts?.length > 0 && <div className="rounded-xl border border-danger-200 bg-danger-50 p-4 text-sm text-danger-800">{dialog.preview.conflicts.map((conflict, index) => <p key={index}>{conflict.reason || conflict.message || String(conflict)}{conflict.recordIds?.length ? ` (records ${conflict.recordIds.join(", ")})` : ""}</p>)}</div>}{dialog?.preview && !dialog.preview.conflicts?.length && <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-600 dark:bg-slate-800">This merge will reassign {impact} linked record{impact === 1 ? '' : 's'} and retire the other selected {cfg.label.toLowerCase()}.</p>}<div className="flex justify-end gap-3"><button type="button" onClick={() => setDialog(null)} className="rounded-lg border px-4 py-2">Cancel</button><button type="button" disabled={!dialog?.preview || dialog.preview.conflicts?.length || working} onClick={merge} className="rounded-lg bg-primary-600 px-4 py-2 font-semibold text-white disabled:opacity-40">{working ? 'Merging…' : 'Confirm merge'}</button></div></div></Modal>
    </div>;
}
