-- Moved: use database/scripts/recompute_wac.sql
-- This placeholder remains for backward compatibility with docs.
-- Usage:
--   psql -h <host> -U <user> -d <db> -f database/scripts/recompute_wac.sql
