-- Moved: use database/scripts/set_wac_from_last_cost.sql
-- This placeholder remains for backward compatibility with docs.
-- Usage:
--   psql -h <host> -U <user> -d <db> -f database/scripts/set_wac_from_last_cost.sql
