-- Migration: 20260813_18_hr_pay_component_assignable.sql
-- Description: Distinguish components the payroll engine GENERATES from those a
--              human may ASSIGN to an employee.
--
-- Without this, the component picker offered codes like BASIC, OT_REG and
-- SSS_LOAN. Assigning BASIC as a recurring allowance would have added a second
-- basic-pay line on top of the one the engine already computes — silently
-- doubling someone's salary.
--
-- Loan codes are excluded too: an instalment comes from employee_loan, which
-- tracks the outstanding balance and stops when the loan is paid off. A
-- recurring component would deduct forever.
--
-- `is_statutory` was already excluded by the endpoint, but that only covered
-- the contribution codes, not the rest of the engine-generated set.

BEGIN;

ALTER TABLE pay_component
    ADD COLUMN IF NOT EXISTS is_assignable BOOLEAN NOT NULL DEFAULT true;

COMMENT ON COLUMN pay_component.is_assignable IS
    'True when a human may attach this component to an employee. False for codes the payroll engine produces itself (basic pay, overtime, holiday and leave pay, absences, statutory contributions) and for loan codes driven by employee_loan.';

UPDATE pay_component
SET is_assignable = false
WHERE component_code IN (
    -- Computed from the DTR and the compensation record
    'BASIC', 'OT_REG', 'OT_REST', 'HOLIDAY_REG', 'HOLIDAY_SPECIAL',
    'NIGHT_DIFF', 'LEAVE_PAY', 'ABSENCE', 'LATE', 'UNDERTIME',
    -- Generated by the 13th-month run type
    'THIRTEENTH_MONTH',
    -- Driven by employee_loan, which tracks the balance
    'SSS_LOAN', 'HDMF_LOAN', 'CASH_ADVANCE'
) OR is_statutory = true;

COMMIT;
