-- Migration: Seed vehicle taxonomy reference data (Vehicle Fitment Phase 1b)
-- Reviewed reference list of makes/models/engines relevant to this business's
-- market, provided by the user (Toyota, Mitsubishi, Suzuki, Ford, Nissan, Honda,
-- Isuzu, Hyundai, Kia, Chevrolet, Foton, JAC, BYD, MG, Geely, Chery, Chana,
-- Mitsubishi Fuso, Hino, UD Trucks/Nissan Diesel). Establishes the taxonomy as a
-- real reference set up front instead of building it up reactively from
-- fitment entries alone -- see Phase 1b of the vehicle fitment plan. Purely
-- additive: matches existing makes/models/engines case-insensitively and skips
-- them, never overwrites an existing row's attributes.
-- 2026-09-09

BEGIN;

-- 1. New makes (case-insensitive skip if already present)
INSERT INTO public.vehicle_make (make_name)
SELECT v.make_name FROM (VALUES
    ('Toyota'),
    ('Mitsubishi'),
    ('Suzuki'),
    ('Ford'),
    ('Nissan'),
    ('Honda'),
    ('Isuzu'),
    ('Hyundai'),
    ('Kia'),
    ('Chevrolet'),
    ('Foton'),
    ('JAC'),
    ('BYD'),
    ('MG'),
    ('Geely'),
    ('Chery'),
    ('Chana'),
    ('Mitsubishi Fuso'),
    ('Hino'),
    ('UD Trucks / Nissan Diesel')
) AS v(make_name)
WHERE NOT EXISTS (SELECT 1 FROM public.vehicle_make vm WHERE lower(vm.make_name) = lower(v.make_name));

-- 2. New models (case-insensitive skip if already present under the resolved make)
INSERT INTO public.vehicle_model (make_id, model_name)
SELECT vmk.make_id, v.model_name FROM (VALUES
    ('Toyota', 'Vios'),
    ('Toyota', 'Wigo'),
    ('Toyota', 'Innova'),
    ('Toyota', 'Avanza'),
    ('Toyota', 'Veloz'),
    ('Toyota', 'Fortuner'),
    ('Toyota', 'Hilux'),
    ('Toyota', 'Hiace'),
    ('Toyota', 'Tamaraw FX'),
    ('Toyota', 'Revo'),
    ('Toyota', 'Corolla'),
    ('Toyota', 'Corolla Altis'),
    ('Toyota', 'Corolla Cross'),
    ('Toyota', 'Camry'),
    ('Toyota', 'Rush'),
    ('Toyota', 'Raize'),
    ('Toyota', 'Land Cruiser'),
    ('Toyota', 'Land Cruiser Prado'),
    ('Toyota', 'RAV4'),
    ('Toyota', 'Yaris'),
    ('Mitsubishi', 'Mirage'),
    ('Mitsubishi', 'Mirage G4'),
    ('Mitsubishi', 'Xpander'),
    ('Mitsubishi', 'Montero Sport'),
    ('Mitsubishi', 'L300'),
    ('Mitsubishi', 'Adventure'),
    ('Mitsubishi', 'Strada'),
    ('Mitsubishi', 'Fuzion'),
    ('Mitsubishi', 'ASX'),
    ('Mitsubishi', 'Outlander'),
    ('Suzuki', 'Dzire'),
    ('Suzuki', 'Swift'),
    ('Suzuki', 'Ertiga'),
    ('Suzuki', 'XL7'),
    ('Suzuki', 'Vitara'),
    ('Suzuki', 'APV'),
    ('Suzuki', 'Jimny'),
    ('Suzuki', 'S-Presso'),
    ('Suzuki', 'Every / Multicab'),
    ('Suzuki', 'Carry'),
    ('Ford', 'Ranger'),
    ('Ford', 'Everest'),
    ('Ford', 'EcoSport'),
    ('Ford', 'Territory'),
    ('Ford', 'Focus'),
    ('Ford', 'Fiesta'),
    ('Nissan', 'Navara'),
    ('Nissan', 'Terra'),
    ('Nissan', 'Almera'),
    ('Nissan', 'X-Trail'),
    ('Nissan', 'Urvan'),
    ('Nissan', 'Patrol'),
    ('Honda', 'City'),
    ('Honda', 'Civic'),
    ('Honda', 'CR-V'),
    ('Honda', 'BR-V'),
    ('Honda', 'Brio'),
    ('Honda', 'Mobilio'),
    ('Honda', 'HR-V'),
    ('Isuzu', 'Crosswind'),
    ('Isuzu', 'Panther'),
    ('Isuzu', 'D-Max'),
    ('Isuzu', 'mu-X'),
    ('Isuzu', 'Traviz'),
    ('Isuzu', 'Traga'),
    ('Isuzu', 'Bison'),
    ('Isuzu', 'Elf'),
    ('Isuzu', 'NLR'),
    ('Isuzu', 'NPR'),
    ('Isuzu', 'NKR'),
    ('Isuzu', 'NQR'),
    ('Isuzu', 'Forward'),
    ('Isuzu', 'FRR'),
    ('Isuzu', 'FSR'),
    ('Isuzu', 'FVR'),
    ('Isuzu', 'FVM'),
    ('Isuzu', 'Giga'),
    ('Isuzu', 'CVR'),
    ('Isuzu', 'C&E Series'),
    ('Hyundai', 'Accent'),
    ('Hyundai', 'Elantra'),
    ('Hyundai', 'Tucson'),
    ('Hyundai', 'Santa Fe'),
    ('Hyundai', 'Starex'),
    ('Hyundai', 'Grand Starex'),
    ('Hyundai', 'H100'),
    ('Hyundai', 'Porter'),
    ('Hyundai', 'Porter II'),
    ('Hyundai', 'Reina'),
    ('Hyundai', 'Stargazer'),
    ('Hyundai', 'Mighty'),
    ('Kia', 'Soluto'),
    ('Kia', 'Rio'),
    ('Kia', 'Seltos'),
    ('Kia', 'Sportage'),
    ('Kia', 'Carnival'),
    ('Kia', 'Sorento'),
    ('Kia', 'K2500'),
    ('Kia', 'K2500 Karga'),
    ('Kia', 'K2700'),
    ('Kia', 'Bongo'),
    ('Kia', 'Bongo III'),
    ('Chevrolet', 'Trailblazer'),
    ('Chevrolet', 'Colorado'),
    ('Chevrolet', 'Spin'),
    ('Foton', 'Tornado'),
    ('Foton', 'Thunder'),
    ('Foton', 'Toplander'),
    ('Foton', 'View Traveller'),
    ('Foton', 'Gratour'),
    ('JAC', 'Sunray'),
    ('JAC', 'N-Series'),
    ('BYD', 'Atto 3'),
    ('BYD', 'Dolphin'),
    ('BYD', 'Seagull'),
    ('BYD', 'Sealion'),
    ('BYD', 'Shark'),
    ('MG', 'MG5'),
    ('MG', 'ZS'),
    ('MG', 'RX5'),
    ('MG', 'HS'),
    ('Geely', 'Coolray'),
    ('Geely', 'Okavango'),
    ('Geely', 'Emgrand'),
    ('Chery', 'Tiggo 2'),
    ('Chery', 'Tiggo 4'),
    ('Chery', 'Tiggo 7'),
    ('Chery', 'Tiggo 8'),
    ('Chana', 'Multicab'),
    ('Chana', 'Bravo'),
    ('Mitsubishi Fuso', 'Canter'),
    ('Mitsubishi Fuso', 'Fighter'),
    ('Mitsubishi Fuso', 'Fuso Super Great'),
    ('Mitsubishi Fuso', 'Fuso The Great'),
    ('Mitsubishi Fuso', 'Rosa'),
    ('Hino', '300 Series (Dutro)'),
    ('Hino', 'Dutro'),
    ('Hino', '500 Series'),
    ('Hino', 'Ranger'),
    ('Hino', '700 Series (Profia)'),
    ('Hino', 'Rosa'),
    ('UD Trucks / Nissan Diesel', 'Condor'),
    ('UD Trucks / Nissan Diesel', 'Big Thumb'),
    ('UD Trucks / Nissan Diesel', 'Quon')
) AS v(make_name, model_name)
JOIN public.vehicle_make vmk ON lower(vmk.make_name) = lower(v.make_name)
WHERE NOT EXISTS (
    SELECT 1 FROM public.vehicle_model existing
    WHERE existing.make_id = vmk.make_id AND lower(existing.model_name) = lower(v.model_name)
);

-- 3. New engines with displacement/fuel type (case-insensitive skip if already
--    present -- an existing engine's attributes are never overwritten here;
--    see the Phase 1a migration for backfilling the pre-existing 12 engines).
INSERT INTO public.engine (engine_code, displacement_liters, fuel_type)
SELECT v.engine_code, v.displacement_liters, v.fuel_type FROM (VALUES
    ('2NZ-FE', 1.3, 'gasoline'),
    ('1NZ-FE', 1.5, 'gasoline'),
    ('1NR-FE', 1.3, 'gasoline'),
    ('2NR-FE', 1.5, 'gasoline'),
    ('1KR-DE', 1.0, 'gasoline'),
    ('1KR-VE', 1.0, 'gasoline'),
    ('2KD-FTV', 2.5, 'diesel'),
    ('2GD-FTV', 2.4, 'diesel'),
    ('1TR-FE', 2.0, 'gasoline'),
    ('K3-VE', 1.3, 'gasoline'),
    ('3SZ-VE', 1.5, 'gasoline'),
    ('1NR-VE', 1.3, 'gasoline'),
    ('2NR-VE', 1.5, 'gasoline'),
    ('1KD-FTV', 3.0, 'diesel'),
    ('1GD-FTV', 2.8, 'diesel'),
    ('2TR-FE', 2.7, 'gasoline'),
    ('5L', 3.0, 'diesel'),
    ('2L', 2.4, 'diesel'),
    ('3L', 2.8, 'diesel'),
    ('5K', 1.5, 'gasoline'),
    ('2C', 2.0, 'diesel'),
    ('7K-E', 1.8, 'gasoline'),
    ('1RZ-E', 2.0, 'gasoline'),
    ('2E', 1.3, 'gasoline'),
    ('4A-FE', 1.6, 'gasoline'),
    ('7A-FE', 1.8, 'gasoline'),
    ('3ZZ-FE', 1.6, 'gasoline'),
    ('1ZZ-FE', 1.8, 'gasoline'),
    ('1ZR-FE', 1.6, 'gasoline'),
    ('2ZR-FE', 1.8, 'gasoline'),
    ('2ZR-FXE', 1.8, 'hybrid'),
    ('1AZ-FE', 2.0, 'gasoline'),
    ('2AZ-FE', 2.4, 'gasoline'),
    ('2AR-FE', 2.5, 'gasoline'),
    ('A25A-FXS', 2.5, 'hybrid'),
    ('1KR-VET', 1.0, 'gasoline'),
    ('WA-VE', 1.2, 'gasoline'),
    ('1HZ', 4.2, 'diesel'),
    ('1HD-FTE', 4.2, 'diesel'),
    ('1VD-FTV', 4.5, 'diesel'),
    ('F33A-FTV', 3.3, 'diesel'),
    ('1KZ-TE', 3.0, 'diesel'),
    ('3A92', 1.2, 'gasoline'),
    ('4A91', 1.5, 'gasoline'),
    ('4D56-HP', 2.5, 'diesel'),
    ('4N15', 2.4, 'diesel'),
    ('6B31', 3.0, 'gasoline'),
    ('4D56', 2.5, 'diesel'),
    ('4G63', 2.0, 'gasoline'),
    ('4N16', 2.4, 'diesel'),
    ('4G64', 2.4, 'gasoline'),
    ('4B11', 2.0, 'gasoline'),
    ('4B12', 2.4, 'gasoline'),
    ('4B12-PHEV', 2.4, 'hybrid'),
    ('K12M', 1.2, 'gasoline'),
    ('K12N', 1.2, 'gasoline'),
    ('K14B', 1.4, 'gasoline'),
    ('K15B', 1.5, 'gasoline'),
    ('K15C', 1.5, 'mild_hybrid'),
    ('G16B', 1.6, 'gasoline'),
    ('J20A', 2.0, 'gasoline'),
    ('H25A', 2.5, 'gasoline'),
    ('M16A', 1.6, 'gasoline'),
    ('K14C', 1.4, 'gasoline'),
    ('G16A', 1.6, 'gasoline'),
    ('G13BB', 1.3, 'gasoline'),
    ('M13A', 1.3, 'gasoline'),
    ('K10B', 1.0, 'gasoline'),
    ('K10C', 1.0, 'gasoline'),
    ('F6A', 0.66, 'gasoline'),
    ('K6A', 0.66, 'gasoline'),
    ('K15B-C', 1.5, 'gasoline'),
    ('WL-T', 2.5, 'diesel'),
    ('P4AT', 2.2, 'diesel'),
    ('P5AT', 3.2, 'diesel'),
    ('EcoBlue 2.0 Single-Turbo', 2.0, 'diesel'),
    ('EcoBlue 2.0 Bi-Turbo', 2.0, 'diesel'),
    ('1.5L Ti-VCT', 1.5, 'gasoline'),
    ('1.0L EcoBoost', 1.0, 'gasoline'),
    ('JX4G15', 1.5, 'gasoline'),
    ('4E15', 1.5, 'gasoline'),
    ('1.6L Ti-VCT', 1.6, 'gasoline'),
    ('2.0L GDI', 2.0, 'gasoline'),
    ('2.0L TDCi', 2.0, 'diesel'),
    ('YD25DDTi', 2.5, 'diesel'),
    ('YS23DDTT', 2.3, 'diesel'),
    ('HR15DE', 1.5, 'gasoline'),
    ('HR12DE', 1.2, 'gasoline'),
    ('HRA0', 1.0, 'gasoline'),
    ('QR20DE', 2.0, 'gasoline'),
    ('QR25DE', 2.5, 'gasoline'),
    ('MR20DD', 2.0, 'hybrid'),
    ('TD27', 2.7, 'diesel'),
    ('ZD30DDTi', 3.0, 'diesel'),
    ('TD42', 4.2, 'diesel'),
    ('VK56VD', 5.6, 'gasoline'),
    ('L13A', 1.3, 'gasoline'),
    ('L15A', 1.5, 'gasoline'),
    ('L15Z', 1.5, 'gasoline'),
    ('L15ZF', 1.5, 'gasoline'),
    ('LEB-MMD', 1.5, 'hybrid'),
    ('D15', 1.5, 'gasoline'),
    ('D16', 1.6, 'gasoline'),
    ('B16A', 1.6, 'gasoline'),
    ('D17A', 1.7, 'gasoline'),
    ('R18A', 1.8, 'gasoline'),
    ('K20A', 2.0, 'gasoline'),
    ('L15B7', 1.5, 'gasoline'),
    ('L15BG', 1.5, 'gasoline'),
    ('B20B', 2.0, 'gasoline'),
    ('B20Z', 2.0, 'gasoline'),
    ('K24A', 2.4, 'gasoline'),
    ('K24Z', 2.4, 'gasoline'),
    ('L15BE', 1.5, 'gasoline'),
    ('N16A', 1.6, 'diesel'),
    ('LFB', 2.0, 'hybrid'),
    ('L15Z1', 1.5, 'gasoline'),
    ('L12B', 1.2, 'gasoline'),
    ('L13Z', 1.3, 'gasoline'),
    ('R18Z', 1.8, 'gasoline'),
    ('L15C3', 1.5, 'gasoline'),
    ('4JA1', 2.5, 'diesel'),
    ('4JA1-L', 2.5, 'diesel'),
    ('4JH1-TC', 3.0, 'diesel'),
    ('4JK1-TC', 2.5, 'diesel'),
    ('4JJ1-TC', 3.0, 'diesel'),
    ('4JJ1-TCX', 3.0, 'diesel'),
    ('RZ4E-TC', 1.9, 'diesel'),
    ('4JJ3-TCX', 3.0, 'diesel'),
    ('4JB1', 2.8, 'diesel'),
    ('4BD1', 3.9, 'diesel'),
    ('4BD2', 3.9, 'diesel'),
    ('4HF1', 4.3, 'diesel'),
    ('4HG1', 4.6, 'diesel'),
    ('4HK1', 5.2, 'diesel'),
    ('4JJ1', 3.0, 'diesel'),
    ('C240', 2.4, 'diesel'),
    ('6BB1', 5.4, 'diesel'),
    ('6BD1', 5.8, 'diesel'),
    ('6BF1', 6.1, 'diesel'),
    ('6BG1', 6.5, 'diesel'),
    ('6HE1', 7.1, 'diesel'),
    ('6HH1', 8.2, 'diesel'),
    ('6HK1', 7.8, 'diesel'),
    ('6WA1', 12.0, 'diesel'),
    ('6WF1', 14.3, 'diesel'),
    ('6WG1', 15.7, 'diesel'),
    ('6UZ1', 9.8, 'diesel'),
    ('10PA1', 12.5, 'diesel'),
    ('10PB1', 14.0, 'diesel'),
    ('10PC1', 15.0, 'diesel'),
    ('10PD1', 16.7, 'diesel'),
    ('10PE1', 19.0, 'diesel'),
    ('D4FB', 1.6, 'diesel'),
    ('G4FA', 1.4, 'gasoline'),
    ('G4LC', 1.4, 'gasoline'),
    ('G4FG', 1.6, 'gasoline'),
    ('G4NB', 1.8, 'gasoline'),
    ('G4NA', 2.0, 'gasoline'),
    ('D4EA', 2.0, 'diesel'),
    ('D4HA', 2.0, 'diesel'),
    ('D4EB', 2.2, 'diesel'),
    ('D4HB', 2.2, 'diesel'),
    ('D4BH', 2.5, 'diesel'),
    ('D4CB', 2.5, 'diesel'),
    ('D4BA', 2.5, 'diesel'),
    ('D4BX', 2.5, 'diesel'),
    ('D4BB', 2.6, 'diesel'),
    ('G4FL', 1.5, 'gasoline'),
    ('D4GA', 3.9, 'diesel'),
    ('D4DB', 3.9, 'diesel'),
    ('D4DC', 3.9, 'diesel'),
    ('D4DD', 3.9, 'diesel'),
    ('G4NH', 2.0, 'gasoline'),
    ('J3', 2.9, 'diesel'),
    ('D4HE', 2.2, 'diesel'),
    ('J2', 2.7, 'diesel'),
    ('JT', 3.0, 'diesel'),
    ('XLD25', 2.5, 'diesel'),
    ('XLD28', 2.8, 'diesel'),
    ('GM 1.5L', 1.5, 'gasoline'),
    ('1.3L Multijet', 1.3, 'diesel'),
    ('Cummins ISF 2.8', 2.8, 'diesel'),
    ('Cummins ISF 3.8', 3.8, 'diesel'),
    ('Aucan 2.0', 2.0, 'diesel'),
    ('DAM12R', 1.2, 'gasoline'),
    ('DAM15R', 1.5, 'gasoline'),
    ('HFC4DA1', 2.8, 'diesel'),
    ('TZ200XSQ', NULL, 'electric'),
    ('TZ180XSF', NULL, 'electric'),
    ('TZ180XSH', NULL, 'electric'),
    ('TZ200XYAT', NULL, 'electric'),
    ('BYD476ZQC', 1.5, 'hybrid'),
    ('BYD476ZQC + Dual Motors', 1.5, 'hybrid'),
    ('15S4C', 1.5, 'gasoline'),
    ('15E4E', 1.5, 'gasoline'),
    ('20L4E', 2.0, 'gasoline'),
    ('JLH-3G15TD', 1.5, 'mild_hybrid'),
    ('JLC-4G15B', 1.5, 'gasoline'),
    ('SQRE4G15', 1.5, 'gasoline'),
    ('SQRE4T15', 1.5, 'gasoline'),
    ('SQRF4J16', 1.6, 'gasoline'),
    ('JL465Q', 1.0, 'gasoline'),
    ('JL466Q', 1.1, 'gasoline'),
    ('4D30', 3.3, 'diesel'),
    ('4D31', 3.3, 'diesel'),
    ('4D32', 3.6, 'diesel'),
    ('4D33', 4.2, 'diesel'),
    ('4D34', 3.9, 'diesel'),
    ('4D35', 4.6, 'diesel'),
    ('4D36', 3.6, 'diesel'),
    ('4M50', 4.9, 'diesel'),
    ('4M51', 5.2, 'diesel'),
    ('6D14', 6.5, 'diesel'),
    ('6D15', 6.9, 'diesel'),
    ('6D16', 7.5, 'diesel'),
    ('6D17', 8.2, 'diesel'),
    ('6M60', 7.5, 'diesel'),
    ('6M61', 8.2, 'diesel'),
    ('6D22', 11.1, 'diesel'),
    ('6D24', 11.9, 'diesel'),
    ('6D40', 12.0, 'diesel'),
    ('6M70', 12.9, 'diesel'),
    ('8DC9', 16.0, 'diesel'),
    ('8DC11', 17.7, 'diesel'),
    ('8M20', 20.1, 'diesel'),
    ('8M21', 21.2, 'diesel'),
    ('8M22', 19.0, 'diesel'),
    ('10M20', 25.1, 'diesel'),
    ('10M21', 26.5, 'diesel'),
    ('6R10', 12.8, 'diesel'),
    ('6R20', 10.7, 'diesel'),
    ('6R30', 12.8, 'diesel'),
    ('W04C', 4.0, 'diesel'),
    ('W04D', 4.0, 'diesel'),
    ('N04C', 4.0, 'diesel'),
    ('J05D', 4.7, 'diesel'),
    ('J05E', 5.1, 'diesel'),
    ('J08C', 8.0, 'diesel'),
    ('J08E', 7.7, 'diesel'),
    ('A09C', 8.9, 'diesel'),
    ('H07C', 6.7, 'diesel'),
    ('H07D', 7.4, 'diesel'),
    ('EH700', 6.4, 'diesel'),
    ('J08D', 7.7, 'diesel'),
    ('A05C', 5.1, 'diesel'),
    ('P11C', 10.5, 'diesel'),
    ('K13C', 12.9, 'diesel'),
    ('F17D', 16.7, 'diesel'),
    ('EK100', 13.3, 'diesel'),
    ('DM100', 4.3, 'diesel'),
    ('DQ100', 4.5, 'diesel'),
    ('EC100', 5.0, 'diesel'),
    ('FE6', 6.9, 'diesel'),
    ('FE6T', 6.9, 'diesel'),
    ('PE6', 11.7, 'diesel'),
    ('PF6', 12.5, 'diesel'),
    ('RF8', 17.0, 'diesel'),
    ('RG8', 18.0, 'diesel'),
    ('GH13', 12.8, 'diesel')
) AS v(engine_code, displacement_liters, fuel_type)
WHERE NOT EXISTS (SELECT 1 FROM public.engine e WHERE lower(e.engine_code) = lower(v.engine_code));

-- 4. Vehicle <-> engine fitment mappings (model_id, engine_id), year range NULL
--    (not tracked by the source list) -- unbounded, i.e. no year restriction.
INSERT INTO public.vehicle_engine_fitment (model_id, engine_id, year_start, year_end)
SELECT vmd.model_id, e.engine_id, v.year_start::int, v.year_end::int FROM (VALUES
    ('Toyota', 'Vios', '2NZ-FE', NULL, NULL),
    ('Toyota', 'Vios', '1NZ-FE', NULL, NULL),
    ('Toyota', 'Vios', '1NR-FE', NULL, NULL),
    ('Toyota', 'Vios', '2NR-FE', NULL, NULL),
    ('Toyota', 'Wigo', '1KR-DE', NULL, NULL),
    ('Toyota', 'Wigo', '1KR-VE', NULL, NULL),
    ('Toyota', 'Innova', '2KD-FTV', NULL, NULL),
    ('Toyota', 'Innova', '2GD-FTV', NULL, NULL),
    ('Toyota', 'Innova', '1TR-FE', NULL, NULL),
    ('Toyota', 'Avanza', 'K3-VE', NULL, NULL),
    ('Toyota', 'Avanza', '3SZ-VE', NULL, NULL),
    ('Toyota', 'Avanza', '1NR-VE', NULL, NULL),
    ('Toyota', 'Avanza', '2NR-VE', NULL, NULL),
    ('Toyota', 'Veloz', '2NR-VE', NULL, NULL),
    ('Toyota', 'Fortuner', '2KD-FTV', NULL, NULL),
    ('Toyota', 'Fortuner', '1KD-FTV', NULL, NULL),
    ('Toyota', 'Fortuner', '2GD-FTV', NULL, NULL),
    ('Toyota', 'Fortuner', '1GD-FTV', NULL, NULL),
    ('Toyota', 'Fortuner', '2TR-FE', NULL, NULL),
    ('Toyota', 'Hilux', '5L', NULL, NULL),
    ('Toyota', 'Hilux', '2KD-FTV', NULL, NULL),
    ('Toyota', 'Hilux', '1KD-FTV', NULL, NULL),
    ('Toyota', 'Hilux', '2GD-FTV', NULL, NULL),
    ('Toyota', 'Hilux', '1GD-FTV', NULL, NULL),
    ('Toyota', 'Hiace', '2L', NULL, NULL),
    ('Toyota', 'Hiace', '3L', NULL, NULL),
    ('Toyota', 'Hiace', '5L', NULL, NULL),
    ('Toyota', 'Hiace', '2KD-FTV', NULL, NULL),
    ('Toyota', 'Hiace', '1GD-FTV', NULL, NULL),
    ('Toyota', 'Tamaraw FX', '5K', NULL, NULL),
    ('Toyota', 'Tamaraw FX', '2C', NULL, NULL),
    ('Toyota', 'Revo', '7K-E', NULL, NULL),
    ('Toyota', 'Revo', '1RZ-E', NULL, NULL),
    ('Toyota', 'Revo', '2L', NULL, NULL),
    ('Toyota', 'Corolla', '2E', NULL, NULL),
    ('Toyota', 'Corolla', '4A-FE', NULL, NULL),
    ('Toyota', 'Corolla', '7A-FE', NULL, NULL),
    ('Toyota', 'Corolla Altis', '3ZZ-FE', NULL, NULL),
    ('Toyota', 'Corolla Altis', '1ZZ-FE', NULL, NULL),
    ('Toyota', 'Corolla Altis', '1ZR-FE', NULL, NULL),
    ('Toyota', 'Corolla Altis', '2ZR-FE', NULL, NULL),
    ('Toyota', 'Corolla Altis', '2ZR-FXE', NULL, NULL),
    ('Toyota', 'Corolla Cross', '2ZR-FE', NULL, NULL),
    ('Toyota', 'Corolla Cross', '2ZR-FXE', NULL, NULL),
    ('Toyota', 'Camry', '1AZ-FE', NULL, NULL),
    ('Toyota', 'Camry', '2AZ-FE', NULL, NULL),
    ('Toyota', 'Camry', '2AR-FE', NULL, NULL),
    ('Toyota', 'Camry', 'A25A-FXS', NULL, NULL),
    ('Toyota', 'Rush', '2NR-VE', NULL, NULL),
    ('Toyota', 'Raize', '1KR-VET', NULL, NULL),
    ('Toyota', 'Raize', 'WA-VE', NULL, NULL),
    ('Toyota', 'Land Cruiser', '1HZ', NULL, NULL),
    ('Toyota', 'Land Cruiser', '1HD-FTE', NULL, NULL),
    ('Toyota', 'Land Cruiser', '1VD-FTV', NULL, NULL),
    ('Toyota', 'Land Cruiser', 'F33A-FTV', NULL, NULL),
    ('Toyota', 'Land Cruiser Prado', '1KZ-TE', NULL, NULL),
    ('Toyota', 'Land Cruiser Prado', '1KD-FTV', NULL, NULL),
    ('Toyota', 'Land Cruiser Prado', '1GD-FTV', NULL, NULL),
    ('Toyota', 'Land Cruiser Prado', '2TR-FE', NULL, NULL),
    ('Toyota', 'RAV4', '1AZ-FE', NULL, NULL),
    ('Toyota', 'RAV4', '2AZ-FE', NULL, NULL),
    ('Toyota', 'RAV4', '2AR-FE', NULL, NULL),
    ('Toyota', 'RAV4', 'A25A-FXS', NULL, NULL),
    ('Toyota', 'Yaris', '2NZ-FE', NULL, NULL),
    ('Toyota', 'Yaris', '1NZ-FE', NULL, NULL),
    ('Toyota', 'Yaris', '1NR-FE', NULL, NULL),
    ('Toyota', 'Yaris', '2NR-FE', NULL, NULL),
    ('Mitsubishi', 'Mirage', '3A92', NULL, NULL),
    ('Mitsubishi', 'Mirage G4', '3A92', NULL, NULL),
    ('Mitsubishi', 'Xpander', '4A91', NULL, NULL),
    ('Mitsubishi', 'Montero Sport', '4D56-HP', NULL, NULL),
    ('Mitsubishi', 'Montero Sport', '4N15', NULL, NULL),
    ('Mitsubishi', 'Montero Sport', '6B31', NULL, NULL),
    ('Mitsubishi', 'L300', '4D56', NULL, NULL),
    ('Mitsubishi', 'L300', '4G63', NULL, NULL),
    ('Mitsubishi', 'Adventure', '4D56', NULL, NULL),
    ('Mitsubishi', 'Adventure', '4G63', NULL, NULL),
    ('Mitsubishi', 'Strada', '4D56', NULL, NULL),
    ('Mitsubishi', 'Strada', '4N15', NULL, NULL),
    ('Mitsubishi', 'Strada', '4N16', NULL, NULL),
    ('Mitsubishi', 'Fuzion', '4G64', NULL, NULL),
    ('Mitsubishi', 'ASX', '4B11', NULL, NULL),
    ('Mitsubishi', 'ASX', '4B12', NULL, NULL),
    ('Mitsubishi', 'Outlander', '4B11', NULL, NULL),
    ('Mitsubishi', 'Outlander', '4B12', NULL, NULL),
    ('Mitsubishi', 'Outlander', '4B12-PHEV', NULL, NULL),
    ('Suzuki', 'Dzire', 'K12M', NULL, NULL),
    ('Suzuki', 'Dzire', 'K12N', NULL, NULL),
    ('Suzuki', 'Swift', 'K12M', NULL, NULL),
    ('Suzuki', 'Swift', 'K14B', NULL, NULL),
    ('Suzuki', 'Ertiga', 'K14B', NULL, NULL),
    ('Suzuki', 'Ertiga', 'K15B', NULL, NULL),
    ('Suzuki', 'Ertiga', 'K15C', NULL, NULL),
    ('Suzuki', 'XL7', 'K15B', NULL, NULL),
    ('Suzuki', 'XL7', 'K15C', NULL, NULL),
    ('Suzuki', 'Vitara', 'G16B', NULL, NULL),
    ('Suzuki', 'Vitara', 'J20A', NULL, NULL),
    ('Suzuki', 'Vitara', 'H25A', NULL, NULL),
    ('Suzuki', 'Vitara', 'M16A', NULL, NULL),
    ('Suzuki', 'Vitara', 'K14C', NULL, NULL),
    ('Suzuki', 'APV', 'G16A', NULL, NULL),
    ('Suzuki', 'Jimny', 'G13BB', NULL, NULL),
    ('Suzuki', 'Jimny', 'M13A', NULL, NULL),
    ('Suzuki', 'Jimny', 'K15B', NULL, NULL),
    ('Suzuki', 'S-Presso', 'K10B', NULL, NULL),
    ('Suzuki', 'S-Presso', 'K10C', NULL, NULL),
    ('Suzuki', 'Every / Multicab', 'F6A', NULL, NULL),
    ('Suzuki', 'Every / Multicab', 'K6A', NULL, NULL),
    ('Suzuki', 'Carry', 'G16A', NULL, NULL),
    ('Suzuki', 'Carry', 'K15B-C', NULL, NULL),
    ('Ford', 'Ranger', 'WL-T', NULL, NULL),
    ('Ford', 'Ranger', 'P4AT', NULL, NULL),
    ('Ford', 'Ranger', 'P5AT', NULL, NULL),
    ('Ford', 'Ranger', 'EcoBlue 2.0 Single-Turbo', NULL, NULL),
    ('Ford', 'Ranger', 'EcoBlue 2.0 Bi-Turbo', NULL, NULL),
    ('Ford', 'Everest', 'WL-T', NULL, NULL),
    ('Ford', 'Everest', 'P4AT', NULL, NULL),
    ('Ford', 'Everest', 'P5AT', NULL, NULL),
    ('Ford', 'Everest', 'EcoBlue 2.0 Single-Turbo', NULL, NULL),
    ('Ford', 'Everest', 'EcoBlue 2.0 Bi-Turbo', NULL, NULL),
    ('Ford', 'EcoSport', '1.5L Ti-VCT', NULL, NULL),
    ('Ford', 'EcoSport', '1.0L EcoBoost', NULL, NULL),
    ('Ford', 'Territory', 'JX4G15', NULL, NULL),
    ('Ford', 'Territory', '4E15', NULL, NULL),
    ('Ford', 'Focus', '1.6L Ti-VCT', NULL, NULL),
    ('Ford', 'Focus', '2.0L GDI', NULL, NULL),
    ('Ford', 'Focus', '2.0L TDCi', NULL, NULL),
    ('Ford', 'Fiesta', '1.5L Ti-VCT', NULL, NULL),
    ('Ford', 'Fiesta', '1.6L Ti-VCT', NULL, NULL),
    ('Ford', 'Fiesta', '1.0L EcoBoost', NULL, NULL),
    ('Nissan', 'Navara', 'YD25DDTi', NULL, NULL),
    ('Nissan', 'Navara', 'YS23DDTT', NULL, NULL),
    ('Nissan', 'Terra', 'YD25DDTi', NULL, NULL),
    ('Nissan', 'Terra', 'YS23DDTT', NULL, NULL),
    ('Nissan', 'Almera', 'HR15DE', NULL, NULL),
    ('Nissan', 'Almera', 'HR12DE', NULL, NULL),
    ('Nissan', 'Almera', 'HRA0', NULL, NULL),
    ('Nissan', 'X-Trail', 'QR20DE', NULL, NULL),
    ('Nissan', 'X-Trail', 'QR25DE', NULL, NULL),
    ('Nissan', 'X-Trail', 'MR20DD', NULL, NULL),
    ('Nissan', 'Urvan', 'TD27', NULL, NULL),
    ('Nissan', 'Urvan', 'ZD30DDTi', NULL, NULL),
    ('Nissan', 'Urvan', 'YD25DDTi', NULL, NULL),
    ('Nissan', 'Patrol', 'TD42', NULL, NULL),
    ('Nissan', 'Patrol', 'ZD30DDTi', NULL, NULL),
    ('Nissan', 'Patrol', 'VK56VD', NULL, NULL),
    ('Honda', 'City', 'L13A', NULL, NULL),
    ('Honda', 'City', 'L15A', NULL, NULL),
    ('Honda', 'City', 'L15Z', NULL, NULL),
    ('Honda', 'City', 'L15ZF', NULL, NULL),
    ('Honda', 'City', 'LEB-MMD', NULL, NULL),
    ('Honda', 'Civic', 'D15', NULL, NULL),
    ('Honda', 'Civic', 'D16', NULL, NULL),
    ('Honda', 'Civic', 'B16A', NULL, NULL),
    ('Honda', 'Civic', 'D17A', NULL, NULL),
    ('Honda', 'Civic', 'R18A', NULL, NULL),
    ('Honda', 'Civic', 'K20A', NULL, NULL),
    ('Honda', 'Civic', 'L15B7', NULL, NULL),
    ('Honda', 'Civic', 'L15BG', NULL, NULL),
    ('Honda', 'CR-V', 'B20B', NULL, NULL),
    ('Honda', 'CR-V', 'B20Z', NULL, NULL),
    ('Honda', 'CR-V', 'K20A', NULL, NULL),
    ('Honda', 'CR-V', 'K24A', NULL, NULL),
    ('Honda', 'CR-V', 'K24Z', NULL, NULL),
    ('Honda', 'CR-V', 'L15BE', NULL, NULL),
    ('Honda', 'CR-V', 'N16A', NULL, NULL),
    ('Honda', 'CR-V', 'LFB', NULL, NULL),
    ('Honda', 'BR-V', 'L15Z1', NULL, NULL),
    ('Honda', 'BR-V', 'L15ZF', NULL, NULL),
    ('Honda', 'Brio', 'L12B', NULL, NULL),
    ('Honda', 'Brio', 'L13Z', NULL, NULL),
    ('Honda', 'Mobilio', 'L15Z1', NULL, NULL),
    ('Honda', 'HR-V', 'R18Z', NULL, NULL),
    ('Honda', 'HR-V', 'L15ZF', NULL, NULL),
    ('Honda', 'HR-V', 'L15C3', NULL, NULL),
    ('Isuzu', 'Crosswind', '4JA1', NULL, NULL),
    ('Isuzu', 'Crosswind', '4JA1-L', NULL, NULL),
    ('Isuzu', 'Panther', '4JA1', NULL, NULL),
    ('Isuzu', 'Panther', '4JA1-L', NULL, NULL),
    ('Isuzu', 'D-Max', '4JA1-L', NULL, NULL),
    ('Isuzu', 'D-Max', '4JH1-TC', NULL, NULL),
    ('Isuzu', 'D-Max', '4JK1-TC', NULL, NULL),
    ('Isuzu', 'D-Max', '4JJ1-TC', NULL, NULL),
    ('Isuzu', 'D-Max', '4JJ1-TCX', NULL, NULL),
    ('Isuzu', 'D-Max', 'RZ4E-TC', NULL, NULL),
    ('Isuzu', 'D-Max', '4JJ3-TCX', NULL, NULL),
    ('Isuzu', 'mu-X', '4JK1-TC', NULL, NULL),
    ('Isuzu', 'mu-X', '4JJ1-TCX', NULL, NULL),
    ('Isuzu', 'mu-X', 'RZ4E-TC', NULL, NULL),
    ('Isuzu', 'mu-X', '4JJ3-TCX', NULL, NULL),
    ('Isuzu', 'Traviz', '4JA1-L', NULL, NULL),
    ('Isuzu', 'Traga', '4JA1-L', NULL, NULL),
    ('Isuzu', 'Bison', '4D56', NULL, NULL),
    ('Isuzu', 'Elf', '4JA1', NULL, NULL),
    ('Isuzu', 'Elf', '4JB1', NULL, NULL),
    ('Isuzu', 'Elf', '4BD1', NULL, NULL),
    ('Isuzu', 'Elf', '4BD2', NULL, NULL),
    ('Isuzu', 'Elf', '4HF1', NULL, NULL),
    ('Isuzu', 'Elf', '4HG1', NULL, NULL),
    ('Isuzu', 'Elf', '4HK1', NULL, NULL),
    ('Isuzu', 'Elf', '4JJ1', NULL, NULL),
    ('Isuzu', 'Elf', 'C240', NULL, NULL),
    ('Isuzu', 'NLR', '4JJ1', NULL, NULL),
    ('Isuzu', 'NPR', '4HK1', NULL, NULL),
    ('Isuzu', 'NPR', '4HF1', NULL, NULL),
    ('Isuzu', 'NKR', '4JB1', NULL, NULL),
    ('Isuzu', 'NKR', '4HF1', NULL, NULL),
    ('Isuzu', 'NQR', '4HK1', NULL, NULL),
    ('Isuzu', 'Forward', '6BB1', NULL, NULL),
    ('Isuzu', 'Forward', '6BD1', NULL, NULL),
    ('Isuzu', 'Forward', '6BF1', NULL, NULL),
    ('Isuzu', 'Forward', '6BG1', NULL, NULL),
    ('Isuzu', 'Forward', '6HE1', NULL, NULL),
    ('Isuzu', 'Forward', '6HH1', NULL, NULL),
    ('Isuzu', 'Forward', '6HK1', NULL, NULL),
    ('Isuzu', 'FRR', '6HK1', NULL, NULL),
    ('Isuzu', 'FSR', '6HK1', NULL, NULL),
    ('Isuzu', 'FVR', '6HK1', NULL, NULL),
    ('Isuzu', 'FVM', '6HK1', NULL, NULL),
    ('Isuzu', 'Giga', '6WA1', NULL, NULL),
    ('Isuzu', 'Giga', '6WF1', NULL, NULL),
    ('Isuzu', 'Giga', '6WG1', NULL, NULL),
    ('Isuzu', 'Giga', '6UZ1', NULL, NULL),
    ('Isuzu', 'CVR', '6WA1', NULL, NULL),
    ('Isuzu', 'CVR', '6WF1', NULL, NULL),
    ('Isuzu', 'C&E Series', '10PA1', NULL, NULL),
    ('Isuzu', 'C&E Series', '10PB1', NULL, NULL),
    ('Isuzu', 'C&E Series', '10PC1', NULL, NULL),
    ('Isuzu', 'C&E Series', '10PD1', NULL, NULL),
    ('Isuzu', 'C&E Series', '10PE1', NULL, NULL),
    ('Hyundai', 'Accent', 'D4FB', NULL, NULL),
    ('Hyundai', 'Accent', 'G4FA', NULL, NULL),
    ('Hyundai', 'Accent', 'G4LC', NULL, NULL),
    ('Hyundai', 'Elantra', 'G4FG', NULL, NULL),
    ('Hyundai', 'Elantra', 'G4NB', NULL, NULL),
    ('Hyundai', 'Elantra', 'G4NA', NULL, NULL),
    ('Hyundai', 'Tucson', 'D4EA', NULL, NULL),
    ('Hyundai', 'Tucson', 'D4HA', NULL, NULL),
    ('Hyundai', 'Tucson', 'G4NA', NULL, NULL),
    ('Hyundai', 'Santa Fe', 'D4EB', NULL, NULL),
    ('Hyundai', 'Santa Fe', 'D4HB', NULL, NULL),
    ('Hyundai', 'Starex', 'D4BH', NULL, NULL),
    ('Hyundai', 'Grand Starex', 'D4CB', NULL, NULL),
    ('Hyundai', 'H100', 'D4BA', NULL, NULL),
    ('Hyundai', 'H100', 'D4BX', NULL, NULL),
    ('Hyundai', 'H100', 'D4BB', NULL, NULL),
    ('Hyundai', 'H100', 'D4BH', NULL, NULL),
    ('Hyundai', 'H100', 'D4CB', NULL, NULL),
    ('Hyundai', 'Porter', 'D4BB', NULL, NULL),
    ('Hyundai', 'Porter II', 'D4CB', NULL, NULL),
    ('Hyundai', 'Reina', 'G4LC', NULL, NULL),
    ('Hyundai', 'Stargazer', 'G4FL', NULL, NULL),
    ('Hyundai', 'Mighty', 'D4GA', NULL, NULL),
    ('Hyundai', 'Mighty', 'D4DB', NULL, NULL),
    ('Hyundai', 'Mighty', 'D4DC', NULL, NULL),
    ('Hyundai', 'Mighty', 'D4DD', NULL, NULL),
    ('Kia', 'Soluto', 'G4LC', NULL, NULL),
    ('Kia', 'Rio', 'G4FA', NULL, NULL),
    ('Kia', 'Rio', 'G4LC', NULL, NULL),
    ('Kia', 'Seltos', 'G4FL', NULL, NULL),
    ('Kia', 'Seltos', 'G4NH', NULL, NULL),
    ('Kia', 'Sportage', 'D4HA', NULL, NULL),
    ('Kia', 'Sportage', 'G4NA', NULL, NULL),
    ('Kia', 'Carnival', 'J3', NULL, NULL),
    ('Kia', 'Carnival', 'D4HB', NULL, NULL),
    ('Kia', 'Carnival', 'D4HE', NULL, NULL),
    ('Kia', 'Sorento', 'D4HB', NULL, NULL),
    ('Kia', 'Sorento', 'D4HE', NULL, NULL),
    ('Kia', 'K2500', 'D4BH', NULL, NULL),
    ('Kia', 'K2500', 'D4CB', NULL, NULL),
    ('Kia', 'K2500 Karga', 'D4CB', NULL, NULL),
    ('Kia', 'K2700', 'J2', NULL, NULL),
    ('Kia', 'Bongo', 'D4BH', NULL, NULL),
    ('Kia', 'Bongo', 'JT', NULL, NULL),
    ('Kia', 'Bongo III', 'D4CB', NULL, NULL),
    ('Chevrolet', 'Trailblazer', 'XLD25', NULL, NULL),
    ('Chevrolet', 'Trailblazer', 'XLD28', NULL, NULL),
    ('Chevrolet', 'Colorado', 'XLD25', NULL, NULL),
    ('Chevrolet', 'Colorado', 'XLD28', NULL, NULL),
    ('Chevrolet', 'Spin', 'GM 1.5L', NULL, NULL),
    ('Chevrolet', 'Spin', '1.3L Multijet', NULL, NULL),
    ('Foton', 'Tornado', 'Cummins ISF 2.8', NULL, NULL),
    ('Foton', 'Tornado', 'Cummins ISF 3.8', NULL, NULL),
    ('Foton', 'Tornado', 'Aucan 2.0', NULL, NULL),
    ('Foton', 'Thunder', 'Cummins ISF 2.8', NULL, NULL),
    ('Foton', 'Thunder', 'Aucan 2.0', NULL, NULL),
    ('Foton', 'Toplander', 'Cummins ISF 2.8', NULL, NULL),
    ('Foton', 'View Traveller', 'Cummins ISF 2.8', NULL, NULL),
    ('Foton', 'Gratour', 'DAM12R', NULL, NULL),
    ('Foton', 'Gratour', 'DAM15R', NULL, NULL),
    ('JAC', 'Sunray', 'HFC4DA1', NULL, NULL),
    ('JAC', 'Sunray', 'Cummins ISF 2.8', NULL, NULL),
    ('JAC', 'N-Series', 'Cummins ISF 2.8', NULL, NULL),
    ('JAC', 'N-Series', 'Cummins ISF 3.8', NULL, NULL),
    ('BYD', 'Atto 3', 'TZ200XSQ', NULL, NULL),
    ('BYD', 'Dolphin', 'TZ180XSF', NULL, NULL),
    ('BYD', 'Seagull', 'TZ180XSH', NULL, NULL),
    ('BYD', 'Sealion', 'TZ200XYAT', NULL, NULL),
    ('BYD', 'Sealion', 'BYD476ZQC', NULL, NULL),
    ('BYD', 'Shark', 'BYD476ZQC + Dual Motors', NULL, NULL),
    ('MG', 'MG5', '15S4C', NULL, NULL),
    ('MG', 'ZS', '15S4C', NULL, NULL),
    ('MG', 'ZS', '15E4E', NULL, NULL),
    ('MG', 'RX5', '15E4E', NULL, NULL),
    ('MG', 'HS', '15E4E', NULL, NULL),
    ('MG', 'HS', '20L4E', NULL, NULL),
    ('Geely', 'Coolray', 'JLH-3G15TD', NULL, NULL),
    ('Geely', 'Okavango', 'JLH-3G15TD', NULL, NULL),
    ('Geely', 'Emgrand', 'JLC-4G15B', NULL, NULL),
    ('Chery', 'Tiggo 2', 'SQRE4G15', NULL, NULL),
    ('Chery', 'Tiggo 4', 'SQRE4G15', NULL, NULL),
    ('Chery', 'Tiggo 4', 'SQRE4T15', NULL, NULL),
    ('Chery', 'Tiggo 7', 'SQRE4T15', NULL, NULL),
    ('Chery', 'Tiggo 7', 'SQRF4J16', NULL, NULL),
    ('Chery', 'Tiggo 8', 'SQRE4T15', NULL, NULL),
    ('Chery', 'Tiggo 8', 'SQRF4J16', NULL, NULL),
    ('Chana', 'Multicab', 'JL465Q', NULL, NULL),
    ('Chana', 'Multicab', 'JL466Q', NULL, NULL),
    ('Chana', 'Bravo', 'JL465Q', NULL, NULL),
    ('Mitsubishi Fuso', 'Canter', '4D30', NULL, NULL),
    ('Mitsubishi Fuso', 'Canter', '4D31', NULL, NULL),
    ('Mitsubishi Fuso', 'Canter', '4D32', NULL, NULL),
    ('Mitsubishi Fuso', 'Canter', '4D33', NULL, NULL),
    ('Mitsubishi Fuso', 'Canter', '4D34', NULL, NULL),
    ('Mitsubishi Fuso', 'Canter', '4D35', NULL, NULL),
    ('Mitsubishi Fuso', 'Canter', '4D36', NULL, NULL),
    ('Mitsubishi Fuso', 'Canter', '4M50', NULL, NULL),
    ('Mitsubishi Fuso', 'Canter', '4M51', NULL, NULL),
    ('Mitsubishi Fuso', 'Fighter', '6D14', NULL, NULL),
    ('Mitsubishi Fuso', 'Fighter', '6D15', NULL, NULL),
    ('Mitsubishi Fuso', 'Fighter', '6D16', NULL, NULL),
    ('Mitsubishi Fuso', 'Fighter', '6D17', NULL, NULL),
    ('Mitsubishi Fuso', 'Fighter', '6M60', NULL, NULL),
    ('Mitsubishi Fuso', 'Fighter', '6M61', NULL, NULL),
    ('Mitsubishi Fuso', 'Fuso Super Great', '6D22', NULL, NULL),
    ('Mitsubishi Fuso', 'Fuso Super Great', '6D24', NULL, NULL),
    ('Mitsubishi Fuso', 'Fuso Super Great', '6D40', NULL, NULL),
    ('Mitsubishi Fuso', 'Fuso Super Great', '6M70', NULL, NULL),
    ('Mitsubishi Fuso', 'Fuso Super Great', '8DC9', NULL, NULL),
    ('Mitsubishi Fuso', 'Fuso Super Great', '8DC11', NULL, NULL),
    ('Mitsubishi Fuso', 'Fuso Super Great', '8M20', NULL, NULL),
    ('Mitsubishi Fuso', 'Fuso Super Great', '8M21', NULL, NULL),
    ('Mitsubishi Fuso', 'Fuso Super Great', '8M22', NULL, NULL),
    ('Mitsubishi Fuso', 'Fuso Super Great', '10M20', NULL, NULL),
    ('Mitsubishi Fuso', 'Fuso Super Great', '10M21', NULL, NULL),
    ('Mitsubishi Fuso', 'Fuso Super Great', '6R10', NULL, NULL),
    ('Mitsubishi Fuso', 'Fuso Super Great', '6R20', NULL, NULL),
    ('Mitsubishi Fuso', 'Fuso Super Great', '6R30', NULL, NULL),
    ('Mitsubishi Fuso', 'Fuso The Great', '6D22', NULL, NULL),
    ('Mitsubishi Fuso', 'Fuso The Great', '6D24', NULL, NULL),
    ('Mitsubishi Fuso', 'Fuso The Great', '8DC9', NULL, NULL),
    ('Mitsubishi Fuso', 'Fuso The Great', '8DC11', NULL, NULL),
    ('Mitsubishi Fuso', 'Rosa', '4D33', NULL, NULL),
    ('Mitsubishi Fuso', 'Rosa', '4D34', NULL, NULL),
    ('Mitsubishi Fuso', 'Rosa', '4M50', NULL, NULL),
    ('Hino', '300 Series (Dutro)', 'W04C', NULL, NULL),
    ('Hino', '300 Series (Dutro)', 'W04D', NULL, NULL),
    ('Hino', '300 Series (Dutro)', 'N04C', NULL, NULL),
    ('Hino', '300 Series (Dutro)', 'J05D', NULL, NULL),
    ('Hino', '300 Series (Dutro)', 'J05E', NULL, NULL),
    ('Hino', 'Dutro', 'W04D', NULL, NULL),
    ('Hino', 'Dutro', 'N04C', NULL, NULL),
    ('Hino', '500 Series', 'J08C', NULL, NULL),
    ('Hino', '500 Series', 'J08E', NULL, NULL),
    ('Hino', '500 Series', 'A09C', NULL, NULL),
    ('Hino', 'Ranger', 'H07C', NULL, NULL),
    ('Hino', 'Ranger', 'H07D', NULL, NULL),
    ('Hino', 'Ranger', 'EH700', NULL, NULL),
    ('Hino', 'Ranger', 'J08C', NULL, NULL),
    ('Hino', 'Ranger', 'J08D', NULL, NULL),
    ('Hino', 'Ranger', 'J08E', NULL, NULL),
    ('Hino', 'Ranger', 'A05C', NULL, NULL),
    ('Hino', '700 Series (Profia)', 'P11C', NULL, NULL),
    ('Hino', '700 Series (Profia)', 'K13C', NULL, NULL),
    ('Hino', '700 Series (Profia)', 'F17D', NULL, NULL),
    ('Hino', '700 Series (Profia)', 'EK100', NULL, NULL),
    ('Hino', '700 Series (Profia)', 'DM100', NULL, NULL),
    ('Hino', '700 Series (Profia)', 'DQ100', NULL, NULL),
    ('Hino', '700 Series (Profia)', 'EC100', NULL, NULL),
    ('Hino', 'Rosa', '4D34', NULL, NULL),
    ('UD Trucks / Nissan Diesel', 'Condor', 'FE6', NULL, NULL),
    ('UD Trucks / Nissan Diesel', 'Condor', 'FE6T', NULL, NULL),
    ('UD Trucks / Nissan Diesel', 'Big Thumb', 'PE6', NULL, NULL),
    ('UD Trucks / Nissan Diesel', 'Big Thumb', 'PF6', NULL, NULL),
    ('UD Trucks / Nissan Diesel', 'Big Thumb', 'RF8', NULL, NULL),
    ('UD Trucks / Nissan Diesel', 'Big Thumb', 'RG8', NULL, NULL),
    ('UD Trucks / Nissan Diesel', 'Quon', 'GH13', NULL, NULL)
) AS v(make_name, model_name, engine_code, year_start, year_end)
JOIN public.vehicle_make vmk ON lower(vmk.make_name) = lower(v.make_name)
JOIN public.vehicle_model vmd ON vmd.make_id = vmk.make_id AND lower(vmd.model_name) = lower(v.model_name)
JOIN public.engine e ON lower(e.engine_code) = lower(v.engine_code)
ON CONFLICT (model_id, engine_id) DO NOTHING;

COMMIT;
