-- Migration: 20260911_01_pos_exchange_schema.sql
-- Description: Schema support for the POS Item Exchange ("Change Item") module
-- (docs/plans/2026-09-11_pos-item-exchange-module.md), Phase 1.
--
-- An exchange is two documents that already exist -- a credit_note against the
-- original invoice, and a brand-new invoice for the replacement items -- wired
-- together with three additions:
--
--   1. credit_note_line.is_defective: the cashier's Re-sellable vs Defective /
--      Quarantine call for the returned unit (PRD Decision #4). Drives whether
--      exchangeRoutes.js posts the return as inventory_transaction trans_type
--      'Refund' (back to active stock) or 'Defective Return' (quarantine).
--
--   2. credit_note.exchange_replacement_invoice_id: lets a credit note
--      generated by an exchange point at the new invoice it helped pay for, so
--      Receipt.jsx and soaPdf.js can render "Original Invoice # / New SI #"
--      cross-references (PRD §5.6, §6.3) without re-deriving the pairing.
--
--   3. invoice.exchange_original_invoice_id: the mirror image on the new
--      invoice, pointing back at the invoice it replaced.
--
-- Both link columns are nullable and ON DELETE SET NULL: an exchange pairing is
-- informational cross-referencing, never something a later void/cleanup should
-- be blocked by.
--
-- Also seeds the 'exchange_credit' payment method. The value of a returned
-- item is real settlement, not a discount -- it needs to reduce the new
-- invoice's own amount_paid via the normal invoice_payments / recompute path
-- (exactly like 'store_wallet' already does for a real credit balance), so it
-- must be a payment_methods row. It is NOT an ar_ledger entry point of its
-- own: the value it carries was already recorded once, as the CREDIT_MEMO_APPLIED
-- entry the credit note posted against the *original* invoice. Posting a
-- second ar_ledger entry when this tender is applied to the *new* invoice
-- would count that same value twice. exchangeRoutes.js must skip the
-- arLedger.appendEntry call for this one payment method code -- every other
-- tender type on the replacement invoice (cash, card, GCash, on-account) posts
-- to ar_ledger exactly as invoiceRoutes.js already does.

BEGIN;

ALTER TABLE public.credit_note_line
    ADD COLUMN IF NOT EXISTS is_defective boolean NOT NULL DEFAULT false;

ALTER TABLE public.credit_note
    ADD COLUMN IF NOT EXISTS exchange_replacement_invoice_id integer
        REFERENCES public.invoice(invoice_id) ON DELETE SET NULL;

ALTER TABLE public.invoice
    ADD COLUMN IF NOT EXISTS exchange_original_invoice_id integer
        REFERENCES public.invoice(invoice_id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_credit_note_exchange_replacement_invoice_id
    ON public.credit_note(exchange_replacement_invoice_id);
CREATE INDEX IF NOT EXISTS idx_invoice_exchange_original_invoice_id
    ON public.invoice(exchange_original_invoice_id);

INSERT INTO public.payment_methods (code, name, type, settlement_type, config, enabled, sort_order)
SELECT 'exchange_credit',
       'Exchange Credit (Item Return)',
       'credit',
       'instant',
       '{"change_allowed": false, "requires_reference": false, "requires_receipt_no": false, "settlement_type": "instant"}'::jsonb,
       TRUE,
       9
WHERE NOT EXISTS (SELECT 1 FROM public.payment_methods WHERE code = 'exchange_credit');

COMMIT;
