import React, { useState, useEffect } from 'react';
import { BellOff } from 'lucide-react';
import NotificationItem from './NotificationItem';

const SkeletonRow = () => (
    <div className="animate-pulse flex items-start gap-3 px-4 py-3">
        <div className="h-4 w-4 bg-gray-200 dark:bg-slate-700 rounded-full shrink-0 mt-0.5" />
        <div className="flex-1 space-y-2">
            <div className="h-3 bg-gray-200 dark:bg-slate-700 rounded w-3/4" />
            <div className="h-3 bg-gray-100 dark:bg-slate-700/60 rounded w-full" />
        </div>
        <div className="h-3 w-10 bg-gray-100 dark:bg-slate-700/60 rounded shrink-0" />
    </div>
);

// Only the 50/100/500/600/700/900 steps of the semantic scales exist — they are
// declared in index.css's @theme block, not generated by Tailwind — so classes
// like `text-primary-400` compile to nothing. Stay on the declared steps.
const NotificationPanel = ({
    notifications, loading, error, hasMore,
    unreadCount, unreadOnly, setUnreadOnly,
    loadFirstPage, loadMore,
    markRead, markAllRead, dismiss,
    onNavigate, onClose,
}) => {
    const [activeTab, setActiveTab] = useState(unreadOnly ? 'unread' : 'all');

    // Fetch the first page when the panel mounts (i.e. first opens).
    // Headless UI unmounts the panel on close, so each open triggers a fresh fetch.
    useEffect(() => {
        loadFirstPage(unreadOnly);
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    const switchTab = (tab) => {
        const newUnreadOnly = tab === 'unread';
        setActiveTab(tab);
        setUnreadOnly(newUnreadOnly);
        loadFirstPage(newUnreadOnly);
    };

    const tabCls = (tab) =>
        `px-3 py-1.5 text-sm font-medium rounded-md transition-colors ${
            activeTab === tab
                ? 'bg-primary-100 dark:bg-primary-900/40 text-primary-700 dark:text-primary-100'
                : 'text-gray-500 dark:text-slate-400 hover:text-gray-700 dark:hover:text-slate-200'
        }`;

    return (
        <div className="w-96 max-w-[calc(100vw-2rem)] bg-white dark:bg-slate-900 rounded-xl shadow-xl border border-gray-200 dark:border-slate-700 flex flex-col overflow-hidden">
            {/* Header row */}
            <div className="flex items-center justify-between px-4 py-3 border-b border-gray-100 dark:border-slate-800">
                <span className="font-semibold text-gray-800 dark:text-slate-100">Notifications</span>
                <button
                    type="button"
                    onClick={markAllRead}
                    disabled={unreadCount === 0}
                    className="text-xs text-primary-600 hover:text-primary-700 font-medium disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
                >
                    Mark all as read
                </button>
            </div>

            {/* Filter tabs */}
            <div className="flex items-center gap-1 px-3 py-2 border-b border-gray-100 dark:border-slate-800">
                <button type="button" className={tabCls('all')}    onClick={() => switchTab('all')}>All</button>
                <button type="button" className={tabCls('unread')} onClick={() => switchTab('unread')}>Unread</button>
            </div>

            {/* Scrollable body */}
            <div className="max-h-[26rem] overflow-y-auto divide-y divide-gray-100 dark:divide-slate-800">
                {loading && notifications.length === 0 ? (
                    [...Array(4)].map((_, i) => <SkeletonRow key={i} />)
                ) : error ? (
                    <div className="flex flex-col items-center justify-center gap-3 py-10 px-4">
                        <p className="text-sm text-gray-500 dark:text-slate-400 text-center">
                            Could not load notifications.
                        </p>
                        <button
                            type="button"
                            onClick={() => loadFirstPage(unreadOnly)}
                            className="px-4 py-1.5 text-sm font-medium rounded-lg bg-gray-100 dark:bg-slate-800 text-gray-700 dark:text-slate-300 hover:bg-gray-200 dark:hover:bg-slate-700 transition"
                        >
                            Retry
                        </button>
                    </div>
                ) : notifications.length === 0 ? (
                    <div className="flex flex-col items-center justify-center gap-2 py-12 text-gray-400 dark:text-slate-500">
                        <BellOff className="h-8 w-8" aria-hidden="true" />
                        <p className="text-sm font-medium">You&#39;re all caught up</p>
                    </div>
                ) : (
                    <>
                        {notifications.map(n => (
                            <NotificationItem
                                key={n.notification_id}
                                notification={n}
                                onMarkRead={markRead}
                                onDismiss={dismiss}
                                onNavigate={onNavigate}
                                onClose={onClose}
                            />
                        ))}
                        {hasMore && (
                            <div className="px-4 py-3 text-center">
                                <button
                                    type="button"
                                    onClick={() => loadMore(unreadOnly)}
                                    disabled={loading}
                                    className="text-sm text-primary-600 hover:text-primary-700 font-medium disabled:opacity-50 transition-colors"
                                >
                                    {loading ? 'Loading\u2026' : 'Load more'}
                                </button>
                            </div>
                        )}
                    </>
                )}
            </div>
        </div>
    );
};

export default NotificationPanel;
