import React, { useMemo, useState } from 'react';
import { Alert, FlatList, Text, View, StyleSheet } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import * as Clipboard from 'expo-clipboard'; import * as Haptics from 'expo-haptics';
import apiClient from '../../api/client'; import { usePermission } from '../../hooks/usePermission';
import Screen from '../../components/ui/Screen'; import AppHeader from '../../components/ui/AppHeader'; import Card from '../../components/ui/Card'; import Button from '../../components/ui/Button'; import StatusBadge, { toneForStatus } from '../../components/ui/StatusBadge'; import DeliverySheet from '../../components/purchase-orders/DeliverySheet'; import { LoadingState, ErrorState } from '../../components/ui/States';
import { useTheme } from '@/hooks/use-theme'; import { Spacing, FontSize, FontWeight } from '@/constants/theme'; import { formatPHP } from '@/utils/currency'; import { sharePurchaseOrderPdf } from '@/utils/sharePurchaseOrder'; import { summaryForPurchaseOrder, type PurchaseOrder } from '@/utils/purchaseOrder';
type PoLine = { po_line_id: number; display_name: string; quantity: number | string; unit?: string | null; cost_price: number | string | null };
export default function PurchaseOrderDetailScreen() {
  const theme = useTheme(); const router = useRouter(); const queryClient = useQueryClient(); const { hasPermission } = usePermission(); const { poId } = useLocalSearchParams() as { poId: string }; const [deliveryOpen, setDeliveryOpen] = useState(false); const [busy, setBusy] = useState(false);
  const lists = useQuery<PurchaseOrder[]>({ queryKey: ['purchaseOrderDetail', poId], queryFn: async () => { const statuses = await Promise.all(['Pending', 'Ordered', 'Partially Received'].map(async (status) => (await apiClient.get('/purchase-orders', { params: { status } })).data)); return statuses.flat().filter((po: PurchaseOrder) => String(po.po_id) === String(poId)); } });
  const order = lists.data?.[0]; const lines = useQuery<PoLine[]>({ queryKey: ['poLines', poId], queryFn: async () => (await apiClient.get(`/purchase-orders/${poId}/lines`)).data });
  const orderForSummary = useMemo(() => order && ({ ...order, supplier_name: order.supplier_name || 'Not specified' }), [order]);
  const promptStatus = () => { if (!hasPermission('purchase_orders:edit') || order?.status !== 'Pending') return; Alert.alert(`Mark ${order.po_number} as Ordered?`, 'This records your purchasing status; sharing does not confirm supplier receipt.', [{ text: 'Not yet', style: 'cancel' }, { text: 'Mark Ordered', onPress: markOrdered }]); };
  const markOrdered = async () => { try { setBusy(true); await apiClient.put(`/purchase-orders/${poId}/status`, { status: 'Ordered' }); await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success); queryClient.invalidateQueries({ queryKey: ['purchaseOrders'] }); queryClient.invalidateQueries({ queryKey: ['openPurchaseOrders'] }); queryClient.invalidateQueries({ queryKey: ['purchaseOrderDetail', poId] }); Alert.alert('PO marked Ordered', 'It is ready for receiving when stock arrives.', [{ text: 'View receiving', onPress: () => router.push(`/receiving/${poId}` as never) }, { text: 'OK' }]); } catch (e: any) { Alert.alert('Could not update status', e?.response?.data?.message || 'The purchase order remains Pending.'); } finally { setBusy(false); } };
  const share = async () => { if (!order) return; try { setBusy(true); await sharePurchaseOrderPdf(order.po_id, order.po_number); setDeliveryOpen(false); promptStatus(); } catch (e: any) { Alert.alert('Could not share PDF', e?.message || 'Please try again.'); } finally { setBusy(false); } };
  const copy = async () => { if (!orderForSummary) return; await Clipboard.setStringAsync(summaryForPurchaseOrder(orderForSummary, lines.data || [])); setDeliveryOpen(false); Alert.alert('Order summary copied', 'The summary is on your clipboard.'); promptStatus(); };
  if (lists.isLoading || lines.isLoading) return <Screen><AppHeader title="Purchase order" /><LoadingState /></Screen>; if (lists.error || !order) return <Screen><AppHeader title="Purchase order" /><ErrorState title="Could not load this purchase order" onRetry={() => { lists.refetch(); lines.refetch(); }} /></Screen>;
  return <Screen><AppHeader title={order.po_number || `PO ${poId}`} subtitle={order.supplier_name} /><View style={styles.header}><StatusBadge label={order.status} tone={toneForStatus(order.status)} /><Text style={[styles.total, { color: theme.text }]}>{formatPHP(order.total_amount || 0)}</Text>{order.expected_date ? <Text style={{ color: theme.textMuted, fontSize: FontSize.sm }}>Expected {new Date(order.expected_date).toLocaleDateString('en-PH')}</Text> : null}</View><FlatList data={lines.data || []} keyExtractor={(item) => String(item.po_line_id)} contentContainerStyle={styles.lines} renderItem={({ item }) => <Card><Text style={[styles.name, { color: theme.text }]}>{item.display_name}</Text><Text style={{ color: theme.textSecondary, fontSize: FontSize.sm }}>{item.quantity} {item.unit || 'PCS'} × {formatPHP(item.cost_price || 0)}</Text></Card>} ListFooterComponent={order.notes ? <Text style={[styles.notes, { color: theme.textMuted }]}>Note: {order.notes}</Text> : null} /><View style={[styles.footer, { backgroundColor: theme.surface, borderTopColor: theme.border }]}>{order.status === 'Pending' && hasPermission('purchase_orders:edit') ? <Button label="Review & share" icon="share-outline" fullWidth onPress={() => setDeliveryOpen(true)} loading={busy} /> : <Button label="View / receive" icon="archive-outline" fullWidth onPress={() => router.push(`/receiving/${poId}` as never)} />}</View><DeliverySheet visible={deliveryOpen} onClose={() => setDeliveryOpen(false)} onShare={share} onCopy={copy} /></Screen>;
}
const styles = StyleSheet.create({ header: { padding: Spacing.four, gap: Spacing.one }, total: { fontSize: FontSize.xl, fontWeight: FontWeight.bold }, lines: { padding: Spacing.four, paddingTop: 0, gap: Spacing.two, flexGrow: 1 }, name: { fontSize: FontSize.base, fontWeight: FontWeight.semibold, marginBottom: 3 }, notes: { paddingVertical: Spacing.three, fontSize: FontSize.sm }, footer: { borderTopWidth: StyleSheet.hairlineWidth, padding: Spacing.four } });
