import React, { useCallback, useState } from 'react';
import { View, Text, FlatList, RefreshControl, TouchableOpacity, StyleSheet } from 'react-native';
import { useQuery } from '@tanstack/react-query';
import { useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import apiClient from '../../api/client';
import { usePermission } from '../../hooks/usePermission';
import Screen from '../../components/ui/Screen'; import AppHeader from '../../components/ui/AppHeader'; import Button from '../../components/ui/Button'; import { LoadingState, EmptyState, ErrorState } from '../../components/ui/States';
import PurchaseOrderCard from '../../components/purchase-orders/PurchaseOrderCard';
import { useTheme } from '@/hooks/use-theme'; import { Spacing, Radius, FontSize, FontWeight } from '@/constants/theme'; import type { PurchaseOrder } from '@/utils/purchaseOrder';
type Tab = 'Drafts' | 'Pending' | 'Ordered'; type Draft = { draft_id: number; draft_name: string; draft_data: Record<string, unknown>; last_updated: string; expires_at: string };
export default function PurchaseOrdersScreen() {
  const theme = useTheme(); const router = useRouter(); const { hasPermission } = usePermission(); const [tab, setTab] = useState<Tab>('Drafts'); const [refreshing, setRefreshing] = useState(false);
  const orders = useQuery<PurchaseOrder[]>({ queryKey: ['purchaseOrders', tab], queryFn: async () => (await apiClient.get('/purchase-orders', { params: { status: tab } })).data, enabled: tab !== 'Drafts' });
  const drafts = useQuery<Draft[]>({ queryKey: ['purchaseOrderDrafts'], queryFn: async () => (await apiClient.get('/purchase-orders/drafts')).data, enabled: tab === 'Drafts' && hasPermission('purchase_orders:edit') });
  const refresh = useCallback(async () => { setRefreshing(true); try { await (tab === 'Drafts' ? drafts.refetch() : orders.refetch()); } finally { setRefreshing(false); } }, [tab, drafts, orders]);
  const canEdit = hasPermission('purchase_orders:edit'); const rows = tab === 'Drafts' ? drafts.data ?? [] : orders.data ?? []; const loading = tab === 'Drafts' ? drafts.isLoading : orders.isLoading; const error = tab === 'Drafts' ? drafts.error : orders.error;
  return <Screen><AppHeader title="Smart PO" subtitle={tab === 'Drafts' ? 'Saved work' : `${tab} purchase orders`} right={canEdit ? <TouchableOpacity onPress={() => router.push('/purchase-orders/new')} accessibilityLabel="Create Smart PO"><Ionicons name="add-circle-outline" size={25} color={theme.primary} /></TouchableOpacity> : undefined} />
    <View style={styles.tabs}>{(['Drafts', 'Pending', 'Ordered'] as Tab[]).map((name) => <TouchableOpacity key={name} onPress={() => setTab(name)} style={[styles.tab, { borderColor: theme.border }, tab === name && { backgroundColor: theme.primarySoft, borderColor: theme.primary }]} accessibilityRole="tab" accessibilityState={{ selected: tab === name }}><Text style={{ color: tab === name ? theme.primary : theme.textSecondary, fontWeight: FontWeight.semibold }}>{name}</Text></TouchableOpacity>)}</View>
    {loading ? <LoadingState label="Loading purchase orders…" /> : error ? <ErrorState title="Could not load purchase orders" description="Your last loaded list remains available when possible." onRetry={refresh} /> : <FlatList data={rows} keyExtractor={(item: any) => String(tab === 'Drafts' ? item.draft_id : item.po_id)} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh} colors={[theme.primary]} tintColor={theme.primary} />} contentContainerStyle={styles.list} renderItem={({ item }: any) => tab === 'Drafts' ? <TouchableOpacity style={[styles.draft, { backgroundColor: theme.surface, borderColor: theme.border }]} onPress={() => router.push({ pathname: '/purchase-orders/new', params: { draftId: String(item.draft_id) } })}><Text style={[styles.draftName, { color: theme.text }]}>{item.draft_name}</Text><Text style={{ color: theme.textMuted, fontSize: FontSize.xs }}>Expires {new Date(item.expires_at).toLocaleDateString('en-PH')}</Text></TouchableOpacity> : <PurchaseOrderCard order={item} onPress={() => router.push(`/purchase-orders/${item.po_id}` as never)} />} ListEmptyComponent={<View style={styles.empty}><EmptyState icon={tab === 'Drafts' ? 'document-text-outline' : 'cart-outline'} title={tab === 'Drafts' ? 'No saved drafts' : `No ${tab.toLowerCase()} orders`} description={tab === 'Drafts' ? 'Save draft work while you build a Smart PO.' : 'This queue is clear right now.'} />{canEdit ? <Button label="Create Smart PO" onPress={() => router.push('/purchase-orders/new')} icon="add" /> : null}</View>} />}
  </Screen>;
}
const styles = StyleSheet.create({ tabs: { flexDirection: 'row', padding: Spacing.four, gap: Spacing.two }, tab: { flex: 1, minHeight: 44, justifyContent: 'center', alignItems: 'center', borderWidth: StyleSheet.hairlineWidth, borderRadius: Radius.md }, list: { padding: Spacing.four, paddingTop: 0, gap: Spacing.three, flexGrow: 1 }, draft: { borderWidth: StyleSheet.hairlineWidth, borderRadius: Radius.md, padding: Spacing.four, gap: Spacing.one }, draftName: { fontSize: FontSize.base, fontWeight: FontWeight.semibold }, empty: { flex: 1, alignItems: 'stretch' } });
