import React, { useEffect, useMemo, useState } from 'react';
import { Alert, FlatList, Text, TextInput, TouchableOpacity, View, StyleSheet } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import * as Haptics from 'expo-haptics';
import apiClient from '../../api/client'; import useAuthStore from '../../store/useAuthStore'; import { searchCatalog } from '../../offline/catalogQueries';
import Screen from '../../components/ui/Screen'; import AppHeader from '../../components/ui/AppHeader'; import Card from '../../components/ui/Card'; import Button from '../../components/ui/Button'; import { LoadingState } from '../../components/ui/States';
import SupplierPickerSheet from '../../components/purchase-orders/SupplierPickerSheet'; import SmartPOLineCard from '../../components/purchase-orders/SmartPOLineCard'; import LineEditorSheet from '../../components/purchase-orders/LineEditorSheet';
import { useTheme } from '@/hooks/use-theme'; import { Spacing, Radius, FontSize, FontWeight } from '@/constants/theme'; import { formatPHP } from '@/utils/currency'; import { canReviewPurchaseOrder, lineKey, orderTotal, serializeLines, type SmartPOLine, type Supplier } from '@/utils/purchaseOrder';
type Draft = { draft_id: number; draft_name: string; draft_data: { supplier?: Supplier; supplier_id?: number; lines?: SmartPOLine[]; notes?: string; expected_date?: string } };
const adapted = (results: any[]): SmartPOLine[] => results.map((r, index) => { const part = r.part || null; return { client_id: `${Date.now()}-${index}`, part_id: part?.part_id || null, display_name: part?.display_name || part?.detail || r.raw_description, custom_item_name: part ? null : r.raw_description, unit: r.draft_part_data?.purchase_uom || null, draft_part_data: r.draft_part_data, quantity: Number(r.quantity || 1), cost_price: Number(r.cost_price ?? part?.last_cost ?? 0), match_status: r.match_status, confirmed: ['exact', 'ai', 'unresolved'].includes(r.match_status), candidates: r.candidates || [] }; });
export default function NewPurchaseOrderScreen() {
  const theme = useTheme(); const router = useRouter(); const queryClient = useQueryClient(); const { draftId } = useLocalSearchParams() as { draftId?: string }; const user = useAuthStore((s) => s.user);
  const [supplier, setSupplier] = useState<Supplier | null>(null); const [lines, setLines] = useState<SmartPOLine[]>([]); const [text, setText] = useState(''); const [paste, setPaste] = useState(''); const [showPaste, setShowPaste] = useState(false); const [supplierOpen, setSupplierOpen] = useState(false); const [editing, setEditing] = useState<SmartPOLine | null>(null); const [notes, setNotes] = useState(''); const [expectedDate, setExpectedDate] = useState(''); const [parsing, setParsing] = useState(false); const [saving, setSaving] = useState(false); const [activeDraftId, setActiveDraftId] = useState<number | null>(draftId ? Number(draftId) : null); const [catalogTerm, setCatalogTerm] = useState(''); const [catalogResults, setCatalogResults] = useState<any[]>([]);
  const suppliers = useQuery<Supplier[]>({ queryKey: ['activeSuppliers'], queryFn: async () => (await apiClient.get('/suppliers', { params: { status: 'active' } })).data });
  const draft = useQuery<Draft[]>({ queryKey: ['purchaseOrderDrafts'], queryFn: async () => (await apiClient.get('/purchase-orders/drafts')).data, enabled: Boolean(draftId) });
  useEffect(() => { const saved = draft.data?.find((d) => d.draft_id === Number(draftId)); if (!saved) return; const data = saved.draft_data || {}; setActiveDraftId(saved.draft_id); setSupplier(data.supplier || (data.supplier_id ? (suppliers.data || []).find((s) => s.supplier_id === data.supplier_id) || null : null)); setLines(data.lines || []); setNotes(data.notes || ''); setExpectedDate(data.expected_date || ''); }, [draft.data, draftId, suppliers.data]);
  const total = useMemo(() => orderTotal(lines), [lines]);
  const parse = async (raw: string[]) => { if (!raw.length || raw.length > 50) return Alert.alert('Check the list', 'Enter between 1 and 50 non-empty lines.'); setParsing(true); try { const { data } = await apiClient.post('/purchase-orders/parse-lines', { lines: raw }); setLines((current) => [...current, ...adapted(data)]); setText(''); setPaste(''); setShowPaste(false); await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success); } catch (e: any) { Alert.alert('Could not parse lines', e?.response?.data?.message || 'Please try again.'); } finally { setParsing(false); } };
  const saveDraft = async () => { const draft_data = { supplier, supplier_id: supplier?.supplier_id, lines, notes, expected_date: expectedDate }; try { setSaving(true); if (activeDraftId) await apiClient.put(`/purchase-orders/drafts/${activeDraftId}`, { draft_name: 'Mobile Smart PO', draft_data }); else { const { data } = await apiClient.post('/purchase-orders/drafts', { draft_name: `Mobile Smart PO ${new Date().toLocaleDateString('en-PH')}`, draft_data }); setActiveDraftId(data.draft_id); } queryClient.invalidateQueries({ queryKey: ['purchaseOrderDrafts'] }); Alert.alert('Draft saved', 'This draft expires seven days after its last update.'); } catch (e: any) { Alert.alert('Could not save draft', e?.response?.data?.message || 'Your work remains on this screen.'); } finally { setSaving(false); } };
  const search = async (term: string) => { setCatalogTerm(term); setCatalogResults(term.trim().length >= 2 ? await searchCatalog(term) : []); };
  const addCatalog = (part: any) => { setLines((current) => current.some((l) => l.part_id === part.part_id) ? current : [...current, { client_id: `part-${part.part_id}-${Date.now()}`, part_id: part.part_id, display_name: part.display_name || part.detail, custom_item_name: null, unit: part.measurement_unit || 'PCS', quantity: 1, cost_price: Number(part.last_cost || 0), match_status: 'exact', confirmed: true, candidates: [] }]); setCatalogTerm(''); setCatalogResults([]); };
  const review = async () => { if (!canReviewPurchaseOrder(supplier?.supplier_id || null, lines)) return Alert.alert('Review unavailable', !supplier ? 'Choose a supplier first.' : 'Resolve ambiguous or confirm fuzzy lines before review.'); try { setSaving(true); const { data } = await apiClient.post('/purchase-orders', { supplier_id: supplier!.supplier_id, employee_id: user?.employee_id, expected_date: expectedDate || null, notes: notes || null, lines: serializeLines(lines) }); if (activeDraftId) await apiClient.delete(`/purchase-orders/drafts/${activeDraftId}`); queryClient.invalidateQueries({ queryKey: ['purchaseOrderDrafts'] }); queryClient.invalidateQueries({ queryKey: ['purchaseOrders'] }); router.replace(`/purchase-orders/${data.po_id}` as never); } catch (e: any) { Alert.alert('Could not create purchase order', e?.response?.data?.message || 'No order was created. Please try again.'); } finally { setSaving(false); } };
  if (suppliers.isLoading || (draftId && draft.isLoading)) return <Screen><AppHeader title="Smart PO" /><LoadingState /></Screen>;
  return <Screen><AppHeader title="Smart PO" subtitle={activeDraftId ? 'Draft saved' : 'New purchase order'} right={<TouchableOpacity onPress={saveDraft} disabled={saving} accessibilityLabel="Save draft"><Text style={{ color: theme.primary, fontWeight: FontWeight.bold }}>Save</Text></TouchableOpacity>} /><View style={styles.body}>
    <TouchableOpacity style={[styles.supplier, { backgroundColor: theme.surface, borderColor: theme.border }]} onPress={() => setSupplierOpen(true)} accessibilityLabel="Select supplier"><View><Text style={[styles.label, { color: theme.textMuted }]}>SUPPLIER</Text><Text style={[styles.supplierName, { color: theme.text }]}>{supplier?.supplier_name || 'Select supplier'}</Text></View><Text style={{ color: theme.primary }}>›</Text></TouchableOpacity>
    <Card style={styles.block}><Text style={[styles.heading, { color: theme.text }]}>Add from supplier text</Text><View style={styles.addRow}><TextInput value={text} onChangeText={setText} placeholder="10 NGK CPR8EA-9 @ 135" placeholderTextColor={theme.textMuted} style={[styles.textInput, { color: theme.text, borderColor: theme.border }]} returnKeyType="done" onSubmitEditing={() => parse([text.trim()])} /><Button label={parsing ? 'Parsing…' : 'Add'} size="sm" onPress={() => parse([text.trim()])} disabled={parsing || !text.trim()} /></View><Text style={[styles.tip, { color: theme.textMuted }]}>Quantity + product + @ unit cost</Text><View style={styles.smallActions}><TouchableOpacity onPress={() => setShowPaste(!showPaste)}><Text style={{ color: theme.primary }}>Paste list</Text></TouchableOpacity><TouchableOpacity onPress={() => setCatalogTerm(catalogTerm ? '' : ' ')}><Text style={{ color: theme.primary }}>Search catalog</Text></TouchableOpacity></View>{showPaste && <><TextInput value={paste} onChangeText={setPaste} multiline placeholder="One item per line (up to 50)" placeholderTextColor={theme.textMuted} style={[styles.paste, { color: theme.text, borderColor: theme.border }]} /><Button label="Parse pasted lines" size="sm" onPress={() => parse(paste.split(/\r?\n/).map((v) => v.trim()).filter(Boolean))} disabled={parsing} /></>}{catalogTerm !== '' && <><TextInput value={catalogTerm.trimStart()} onChangeText={search} placeholder="Part name, SKU or number" placeholderTextColor={theme.textMuted} style={[styles.catalogInput, { color: theme.text, borderColor: theme.border }]} />{catalogResults.slice(0, 5).map((part) => <TouchableOpacity key={part.part_id} onPress={() => addCatalog(part)} style={[styles.catalog, { borderColor: theme.border }]}><Text style={{ color: theme.text }}>{part.display_name || part.detail}</Text><Text style={{ color: theme.textMuted, fontSize: FontSize.xs }}>{formatPHP(part.last_cost || 0)}</Text></TouchableOpacity>)}</>}</Card>
    <View style={styles.itemsTitle}><Text style={[styles.heading, { color: theme.text }]}>Items ({lines.length})</Text><Text style={[styles.total, { color: theme.text }]}>{formatPHP(total)}</Text></View><FlatList data={lines} keyExtractor={lineKey} renderItem={({ item }) => <SmartPOLineCard line={item} onEdit={() => setEditing(item)} onRemove={() => Alert.alert('Remove line?', item.display_name, [{ text: 'Cancel', style: 'cancel' }, { text: 'Remove', style: 'destructive', onPress: () => setLines((current) => current.filter((line) => line.client_id !== item.client_id)) }])} />} contentContainerStyle={styles.lines} ListEmptyComponent={<Text style={[styles.tip, { color: theme.textMuted }]}>Add a supplier line or search the catalog to begin.</Text>} />
  </View><View style={[styles.footer, { backgroundColor: theme.surface, borderTopColor: theme.border }]}><Button label={`Review PO · ${lines.length} items · ${formatPHP(total)}`} fullWidth onPress={review} disabled={!canReviewPurchaseOrder(supplier?.supplier_id || null, lines) || saving} loading={saving} /></View><SupplierPickerSheet visible={supplierOpen} suppliers={suppliers.data || []} onClose={() => setSupplierOpen(false)} onPick={(s) => { setSupplier(s); setSupplierOpen(false); }} /><LineEditorSheet line={editing} onClose={() => setEditing(null)} onSave={(next) => { setLines((current) => current.map((line) => line.client_id === next.client_id ? next : line)); setEditing(null); }} /></Screen>;
}
const styles = StyleSheet.create({ body: { flex: 1, padding: Spacing.four, gap: Spacing.three }, supplier: { minHeight: 58, padding: Spacing.three, borderWidth: StyleSheet.hairlineWidth, borderRadius: Radius.md, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, label: { fontSize: FontSize.xs, fontWeight: FontWeight.bold }, supplierName: { fontSize: FontSize.base, fontWeight: FontWeight.semibold, marginTop: 2 }, block: { gap: Spacing.two }, heading: { fontSize: FontSize.base, fontWeight: FontWeight.bold }, addRow: { flexDirection: 'row', gap: Spacing.two, alignItems: 'center' }, textInput: { flex: 1, borderWidth: StyleSheet.hairlineWidth, borderRadius: Radius.sm, paddingHorizontal: Spacing.three, paddingVertical: Spacing.two, fontSize: FontSize.base }, tip: { fontSize: FontSize.xs }, smallActions: { flexDirection: 'row', gap: Spacing.four }, paste: { minHeight: 110, borderWidth: StyleSheet.hairlineWidth, borderRadius: Radius.sm, padding: Spacing.three, textAlignVertical: 'top' }, catalogInput: { borderWidth: StyleSheet.hairlineWidth, borderRadius: Radius.sm, padding: Spacing.three }, catalog: { paddingVertical: Spacing.two, borderBottomWidth: StyleSheet.hairlineWidth }, itemsTitle: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, total: { fontSize: FontSize.base, fontWeight: FontWeight.bold }, lines: { gap: Spacing.two, paddingBottom: 4 }, footer: { borderTopWidth: StyleSheet.hairlineWidth, padding: Spacing.four } });
