import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Alert, KeyboardAvoidingView, Platform, ScrollView, Text, TextInput, TouchableOpacity, View, StyleSheet } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import * as Haptics from 'expo-haptics';
import DateTimePicker from '@react-native-community/datetimepicker';
import apiClient from '../../api/client'; import useAuthStore from '../../store/useAuthStore'; import { searchCatalog } from '../../offline/catalogQueries';
import Screen from '../../components/ui/Screen'; import AppHeader from '../../components/ui/AppHeader'; import Card from '../../components/ui/Card'; import Button from '../../components/ui/Button'; import { LoadingState } from '../../components/ui/States';
import SupplierPickerSheet from '../../components/purchase-orders/SupplierPickerSheet'; import SmartPOLineCard from '../../components/purchase-orders/SmartPOLineCard'; import LineEditorSheet from '../../components/purchase-orders/LineEditorSheet';
import { useTheme } from '@/hooks/use-theme'; import { Spacing, Radius, FontSize, FontWeight } from '@/constants/theme'; import { formatPHP } from '@/utils/currency'; import { canReviewPurchaseOrder, lineKey, orderTotal, serializeLines, type PurchaseOrder, type SmartPOLine, type Supplier } from '@/utils/purchaseOrder';
type Draft = { draft_id: number; draft_name: string; draft_data: { supplier?: Supplier; supplier_id?: number; lines?: SmartPOLine[]; notes?: string; expected_date?: string } };
const adapted = (results: any[]): SmartPOLine[] => results.map((r, index) => { const part = r.part || null; return { client_id: `${Date.now()}-${index}`, part_id: part?.part_id || null, display_name: part?.display_name || part?.detail || r.raw_description, custom_item_name: part ? null : r.raw_description, unit: r.unit || r.draft_part_data?.purchase_uom || null, draft_part_data: r.draft_part_data, quantity: Number(r.quantity || 1), cost_price: Number(r.cost_price ?? part?.last_cost ?? 0), match_status: r.match_status, confirmed: ['exact', 'ai', 'unresolved'].includes(r.match_status), candidates: r.candidates || [] }; });
export default function NewPurchaseOrderScreen() {
  const theme = useTheme(); const router = useRouter(); const queryClient = useQueryClient(); const scrollRef = useRef<ScrollView>(null); const { draftId, poId } = useLocalSearchParams() as { draftId?: string; poId?: string }; const user = useAuthStore((s) => s.user); const isEditingPending = Boolean(poId);
  const [supplier, setSupplier] = useState<Supplier | null>(null); const [lines, setLines] = useState<SmartPOLine[]>([]); const [text, setText] = useState(''); const [paste, setPaste] = useState(''); const [showPaste, setShowPaste] = useState(false); const [supplierOpen, setSupplierOpen] = useState(false); const [editing, setEditing] = useState<SmartPOLine | null>(null); const [notes, setNotes] = useState(''); const [expectedDate, setExpectedDate] = useState(''); const [datePickerOpen, setDatePickerOpen] = useState(false); const [parsing, setParsing] = useState(false); const [saving, setSaving] = useState(false); const [activeDraftId, setActiveDraftId] = useState<number | null>(draftId ? Number(draftId) : null); const [catalogTerm, setCatalogTerm] = useState(''); const [catalogResults, setCatalogResults] = useState<any[]>([]);
  const suppliers = useQuery<Supplier[]>({ queryKey: ['activeSuppliers'], queryFn: async () => (await apiClient.get('/suppliers', { params: { status: 'active' } })).data });
  const draft = useQuery<Draft[]>({ queryKey: ['purchaseOrderDrafts'], queryFn: async () => (await apiClient.get('/purchase-orders/drafts')).data, enabled: Boolean(draftId) });
  const pendingOrder = useQuery<PurchaseOrder | null>({ queryKey: ['pendingPurchaseOrder', poId], queryFn: async () => ((await apiClient.get('/purchase-orders', { params: { status: 'Pending' } })).data as PurchaseOrder[]).find((order) => String(order.po_id) === String(poId)) || null, enabled: isEditingPending });
  const existingLines = useQuery<any[]>({ queryKey: ['poLines', poId], queryFn: async () => (await apiClient.get(`/purchase-orders/${poId}/lines`)).data, enabled: isEditingPending });
  useEffect(() => { const saved = draft.data?.find((d) => d.draft_id === Number(draftId)); if (!saved) return; const data = saved.draft_data || {}; setActiveDraftId(saved.draft_id); setSupplier(data.supplier || (data.supplier_id ? (suppliers.data || []).find((s) => s.supplier_id === data.supplier_id) || null : null)); setLines(data.lines || []); setNotes(data.notes || ''); setExpectedDate(data.expected_date || ''); }, [draft.data, draftId, suppliers.data]);
  useEffect(() => { if (!pendingOrder.data || !existingLines.data) return; setSupplier((suppliers.data || []).find((item) => item.supplier_id === pendingOrder.data?.supplier_id) || { supplier_id: pendingOrder.data.supplier_id, supplier_name: pendingOrder.data.supplier_name }); setLines(existingLines.data.map((line, index) => ({ client_id: `po-line-${line.po_line_id || index}`, part_id: line.part_id || null, display_name: line.display_name || line.custom_item_name || 'Uncataloged item', custom_item_name: line.part_id ? null : line.custom_item_name, unit: line.unit || null, draft_part_data: line.draft_part_data || null, quantity: Number(line.quantity || 1), cost_price: Number(line.cost_price || 0), match_status: line.part_id ? 'exact' : 'unresolved', confirmed: true, candidates: [] }))); setNotes(pendingOrder.data.notes || ''); setExpectedDate(pendingOrder.data.expected_date ? String(pendingOrder.data.expected_date).slice(0, 10) : ''); }, [existingLines.data, pendingOrder.data, suppliers.data]);
  const total = useMemo(() => orderTotal(lines), [lines]);
  const parse = async (raw: string[]) => { if (!raw.length || raw.length > 50) return Alert.alert('Check the list', 'Enter between 1 and 50 non-empty lines.'); setParsing(true); try { const { data } = await apiClient.post('/purchase-orders/parse-lines', { lines: raw }); setLines((current) => [...current, ...adapted(data)]); setText(''); setPaste(''); setShowPaste(false); await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success); } catch (e: any) { Alert.alert('Could not parse lines', e?.response?.data?.message || 'Please try again.'); } finally { setParsing(false); } };
  const saveDraft = async () => { const draft_data = { supplier, supplier_id: supplier?.supplier_id, lines, notes, expected_date: expectedDate }; try { setSaving(true); if (activeDraftId) await apiClient.put(`/purchase-orders/drafts/${activeDraftId}`, { draft_name: 'Mobile Smart PO', draft_data }); else { const { data } = await apiClient.post('/purchase-orders/drafts', { draft_name: `Mobile Smart PO ${new Date().toLocaleDateString('en-PH')}`, draft_data }); setActiveDraftId(data.draft_id); } queryClient.invalidateQueries({ queryKey: ['purchaseOrderDrafts'] }); Alert.alert('Draft saved', 'This draft expires seven days after its last update.'); } catch (e: any) { Alert.alert('Could not save draft', e?.response?.data?.message || 'Your work remains on this screen.'); } finally { setSaving(false); } };
  const search = async (term: string) => { setCatalogTerm(term); setCatalogResults(term.trim().length >= 2 ? await searchCatalog(term) : []); };
  const addCatalog = (part: any) => { setLines((current) => current.some((l) => l.part_id === part.part_id) ? current : [...current, { client_id: `part-${part.part_id}-${Date.now()}`, part_id: part.part_id, display_name: part.display_name || part.detail, custom_item_name: null, unit: part.measurement_unit || 'PCS', quantity: 1, cost_price: Number(part.last_cost || 0), match_status: 'exact', confirmed: true, candidates: [] }]); setCatalogTerm(''); setCatalogResults([]); };
  const savePurchaseOrder = async () => { if (!canReviewPurchaseOrder(supplier?.supplier_id || null, lines)) return Alert.alert('Review unavailable', !supplier ? 'Choose a supplier first.' : 'Resolve ambiguous or confirm fuzzy lines before saving.'); const payload = { supplier_id: supplier!.supplier_id, ...(isEditingPending ? {} : { employee_id: user?.employee_id }), expected_date: expectedDate || null, notes: notes || null, lines: serializeLines(lines) }; try { setSaving(true); const { data } = isEditingPending ? await apiClient.put(`/purchase-orders/${poId}`, payload) : await apiClient.post('/purchase-orders', payload); if (!isEditingPending && activeDraftId) await apiClient.delete(`/purchase-orders/drafts/${activeDraftId}`); queryClient.invalidateQueries({ queryKey: ['purchaseOrderDrafts'] }); queryClient.invalidateQueries({ queryKey: ['purchaseOrders'] }); queryClient.invalidateQueries({ queryKey: ['purchaseOrderDetail', poId] }); queryClient.invalidateQueries({ queryKey: ['poLines', poId] }); router.replace(`/purchase-orders/${isEditingPending ? poId : data.po_id}` as never); } catch (e: any) { Alert.alert(isEditingPending ? 'Could not update purchase order' : 'Could not create purchase order', e?.response?.data?.message || 'No changes were saved. Please try again.'); } finally { setSaving(false); } };
  if (suppliers.isLoading || (draftId && draft.isLoading) || (isEditingPending && (pendingOrder.isLoading || existingLines.isLoading))) return <Screen><AppHeader title="Smart PO" /><LoadingState /></Screen>;
  if (isEditingPending && (!pendingOrder.data || pendingOrder.error || existingLines.error)) return <Screen><AppHeader title="Edit purchase order" /><Text style={[styles.loadError, { color: theme.danger }]}>This Pending purchase order could not be loaded. Please return to the inbox and try again.</Text></Screen>;
  const scrollTo = (y: number) => requestAnimationFrame(() => scrollRef.current?.scrollTo({ y, animated: true }));
  const pickerDate = expectedDate ? new Date(`${expectedDate}T12:00:00`) : new Date();
  const setPickedDate = (_event: unknown, date?: Date) => { if (Platform.OS === 'android') setDatePickerOpen(false); if (!date) return; const yyyy = date.getFullYear(); const mm = String(date.getMonth() + 1).padStart(2, '0'); const dd = String(date.getDate()).padStart(2, '0'); setExpectedDate(`${yyyy}-${mm}-${dd}`); };
  return <Screen><AppHeader title={isEditingPending ? 'Edit Smart PO' : 'Smart PO'} subtitle={isEditingPending ? pendingOrder.data?.po_number : activeDraftId ? 'Draft saved' : 'New purchase order'} right={!isEditingPending ? <TouchableOpacity onPress={saveDraft} disabled={saving} accessibilityLabel="Save draft"><Text style={{ color: theme.primary, fontWeight: FontWeight.bold }}>Save</Text></TouchableOpacity> : undefined} /><KeyboardAvoidingView style={styles.keyboard} behavior={Platform.OS === 'ios' ? 'padding' : undefined} keyboardVerticalOffset={0}><ScrollView ref={scrollRef} contentContainerStyle={styles.body} keyboardShouldPersistTaps="handled" keyboardDismissMode="on-drag" contentInsetAdjustmentBehavior="automatic">
    <TouchableOpacity style={[styles.supplier, { backgroundColor: theme.surface, borderColor: theme.border }]} onPress={() => setSupplierOpen(true)} accessibilityLabel="Select supplier"><View><Text style={[styles.label, { color: theme.textMuted }]}>SUPPLIER</Text><Text style={[styles.supplierName, { color: theme.text }]}>{supplier?.supplier_name || 'Select supplier'}</Text></View><Text style={{ color: theme.primary }}>›</Text></TouchableOpacity>
    <Card style={styles.block}><Text style={[styles.heading, { color: theme.text }]}>Add from supplier text</Text><View style={styles.addRow}><TextInput value={text} onChangeText={setText} placeholder="10 NGK CPR8EA-9 @ 135" placeholderTextColor={theme.textMuted} style={[styles.textInput, { color: theme.text, borderColor: theme.border }]} returnKeyType="done" blurOnSubmit={false} onFocus={() => scrollTo(72)} onSubmitEditing={() => parse([text.trim()])} /><Button label={parsing ? 'Parsing…' : 'Add'} size="sm" onPress={() => parse([text.trim()])} disabled={parsing || !text.trim()} /></View><Text style={[styles.tip, { color: theme.textMuted }]}>Quantity + product + @ unit cost</Text><View style={styles.smallActions}><TouchableOpacity onPress={() => setShowPaste(!showPaste)}><Text style={{ color: theme.primary }}>Paste list</Text></TouchableOpacity><TouchableOpacity onPress={() => setCatalogTerm(catalogTerm ? '' : ' ')}><Text style={{ color: theme.primary }}>Search catalog</Text></TouchableOpacity></View>{showPaste && <><TextInput value={paste} onChangeText={setPaste} multiline placeholder="One item per line (up to 50)" placeholderTextColor={theme.textMuted} onFocus={() => scrollTo(140)} style={[styles.paste, { color: theme.text, borderColor: theme.border }]} /><Button label="Parse pasted lines" size="sm" onPress={() => parse(paste.split(/\r?\n/).map((v) => v.trim()).filter(Boolean))} disabled={parsing} /></>}{catalogTerm !== '' && <><TextInput value={catalogTerm.trimStart()} onChangeText={search} onFocus={() => scrollTo(160)} placeholder="Part name, SKU or number" placeholderTextColor={theme.textMuted} style={[styles.catalogInput, { color: theme.text, borderColor: theme.border }]} />{catalogResults.slice(0, 5).map((part) => <TouchableOpacity key={part.part_id} onPress={() => addCatalog(part)} style={[styles.catalog, { borderColor: theme.border }]}><Text style={{ color: theme.text }}>{part.display_name || part.detail}</Text><Text style={{ color: theme.textMuted, fontSize: FontSize.xs }}>{formatPHP(part.last_cost || 0)}</Text></TouchableOpacity>)}</>}</Card>
    <View style={styles.itemsTitle}><Text style={[styles.heading, { color: theme.text }]}>Items ({lines.length})</Text><Text style={[styles.total, { color: theme.text }]}>{formatPHP(total)}</Text></View>{lines.length ? <View style={styles.lines}>{lines.map((item) => <SmartPOLineCard key={lineKey(item)} line={item} onEdit={() => setEditing(item)} onRemove={() => Alert.alert('Remove line?', item.display_name, [{ text: 'Cancel', style: 'cancel' }, { text: 'Remove', style: 'destructive', onPress: () => setLines((current) => current.filter((line) => line.client_id !== item.client_id)) }])} />)}</View> : <Text style={[styles.tip, { color: theme.textMuted }]}>Add a supplier line or search the catalog to begin.</Text>}<Card style={styles.block}><Text style={[styles.label, { color: theme.textMuted }]}>EXPECTED DATE</Text><TouchableOpacity onPress={() => setDatePickerOpen(true)} accessibilityLabel="Choose expected date" style={[styles.dateTrigger, { borderColor: theme.border, backgroundColor: theme.surfaceMuted }]}><Text style={{ color: expectedDate ? theme.text : theme.textMuted }}>{expectedDate ? new Date(`${expectedDate}T12:00:00`).toLocaleDateString('en-PH') : 'Choose expected date'}</Text></TouchableOpacity>{datePickerOpen && <DateTimePicker value={pickerDate} mode="date" display={Platform.OS === 'ios' ? 'compact' : 'default'} onChange={setPickedDate} />}<Text style={[styles.label, { color: theme.textMuted }]}>NOTE</Text><TextInput value={notes} onChangeText={setNotes} placeholder="Optional purchasing note" placeholderTextColor={theme.textMuted} multiline onFocus={() => requestAnimationFrame(() => scrollRef.current?.scrollToEnd({ animated: true }))} style={[styles.paste, { color: theme.text, borderColor: theme.border }]} /></Card>
  </ScrollView></KeyboardAvoidingView><View style={[styles.footer, { backgroundColor: theme.surface, borderTopColor: theme.border }]}><Button label={isEditingPending ? `Save changes · ${lines.length} items · ${formatPHP(total)}` : `Review PO · ${lines.length} items · ${formatPHP(total)}`} fullWidth onPress={savePurchaseOrder} disabled={!canReviewPurchaseOrder(supplier?.supplier_id || null, lines) || saving} loading={saving} /></View><SupplierPickerSheet visible={supplierOpen} suppliers={suppliers.data || []} onClose={() => setSupplierOpen(false)} onPick={(s) => { setSupplier(s); setSupplierOpen(false); }} /><LineEditorSheet line={editing} onClose={() => setEditing(null)} onSave={(next) => { setLines((current) => current.map((line) => line.client_id === next.client_id ? next : line)); setEditing(null); }} /></Screen>;
}
const styles = StyleSheet.create({ keyboard: { flex: 1 }, body: { flexGrow: 1, padding: Spacing.four, paddingBottom: Spacing.six, gap: Spacing.three }, loadError: { flex: 1, padding: Spacing.four, fontSize: FontSize.base }, supplier: { minHeight: 58, padding: Spacing.three, borderWidth: StyleSheet.hairlineWidth, borderRadius: Radius.md, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, label: { fontSize: FontSize.xs, fontWeight: FontWeight.bold }, supplierName: { fontSize: FontSize.base, fontWeight: FontWeight.semibold, marginTop: 2 }, block: { gap: Spacing.two }, heading: { fontSize: FontSize.base, fontWeight: FontWeight.bold }, addRow: { flexDirection: 'row', gap: Spacing.two, alignItems: 'center' }, textInput: { flex: 1, borderWidth: StyleSheet.hairlineWidth, borderRadius: Radius.sm, paddingHorizontal: Spacing.three, paddingVertical: Spacing.two, fontSize: FontSize.base }, tip: { fontSize: FontSize.xs }, smallActions: { flexDirection: 'row', gap: Spacing.four }, paste: { minHeight: 110, borderWidth: StyleSheet.hairlineWidth, borderRadius: Radius.sm, padding: Spacing.three, textAlignVertical: 'top' }, catalogInput: { borderWidth: StyleSheet.hairlineWidth, borderRadius: Radius.sm, padding: Spacing.three }, dateTrigger: { minHeight: 44, borderWidth: StyleSheet.hairlineWidth, borderRadius: Radius.sm, paddingHorizontal: Spacing.three, justifyContent: 'center' }, catalog: { paddingVertical: Spacing.two, borderBottomWidth: StyleSheet.hairlineWidth }, itemsTitle: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, total: { fontSize: FontSize.base, fontWeight: FontWeight.bold }, lines: { gap: Spacing.two }, footer: { borderTopWidth: StyleSheet.hairlineWidth, padding: Spacing.four } });
