import React, { useEffect, useState } from 'react';
import { Modal, View, Text, TextInput, TouchableOpacity, StyleSheet } from 'react-native';
import { useTheme } from '@/hooks/use-theme';
import { Spacing, Radius, FontSize, FontWeight } from '@/constants/theme';
import type { SmartPOLine } from '@/utils/purchaseOrder';
export default function LineEditorSheet({ line, onClose, onSave }: { line: SmartPOLine | null; onClose: () => void; onSave: (next: SmartPOLine) => void }) {
  const theme = useTheme(); const [quantity, setQuantity] = useState(''); const [cost, setCost] = useState('');
  useEffect(() => { setQuantity(line ? String(line.quantity) : ''); setCost(line ? String(line.cost_price) : ''); }, [line]);
  if (!line) return null;
  const save = () => { const q = Number(quantity); const c = Number(cost); if (!(q > 0) || c < 0 || !Number.isFinite(c)) return; onSave({ ...line, quantity: q, cost_price: c, confirmed: line.match_status === 'fuzzy' ? true : line.confirmed }); };
  return <Modal visible animationType="slide" transparent onRequestClose={onClose}><View style={[styles.backdrop, { backgroundColor: theme.overlay }]}><View style={[styles.sheet, { backgroundColor: theme.surface }]}><Text style={[styles.title, { color: theme.text }]}>Edit line</Text><Text style={[styles.name, { color: theme.textSecondary }]}>{line.display_name}</Text><Text style={[styles.label, { color: theme.textMuted }]}>Quantity</Text><TextInput value={quantity} onChangeText={(v) => setQuantity(v.replace(/[^0-9.]/g, ''))} keyboardType="decimal-pad" style={[styles.input, { color: theme.text, borderColor: theme.border }]} /><Text style={[styles.label, { color: theme.textMuted }]}>Unit cost</Text><TextInput value={cost} onChangeText={(v) => setCost(v.replace(/[^0-9.]/g, ''))} keyboardType="decimal-pad" style={[styles.input, { color: theme.text, borderColor: theme.border }]} /><View style={styles.actions}><TouchableOpacity onPress={onClose}><Text style={{ color: theme.textSecondary }}>Cancel</Text></TouchableOpacity><TouchableOpacity onPress={save} accessibilityLabel="Save line edits"><Text style={{ color: theme.primary, fontWeight: FontWeight.bold }}>Save</Text></TouchableOpacity></View></View></View></Modal>;
}
const styles = StyleSheet.create({ backdrop: { flex: 1, justifyContent: 'flex-end' }, sheet: { borderTopLeftRadius: Radius.lg, borderTopRightRadius: Radius.lg, padding: Spacing.four, gap: Spacing.two }, title: { fontSize: FontSize.lg, fontWeight: FontWeight.bold }, name: { fontSize: FontSize.sm, marginBottom: Spacing.two }, label: { fontSize: FontSize.xs, fontWeight: FontWeight.bold, textTransform: 'uppercase' }, input: { borderWidth: StyleSheet.hairlineWidth, borderRadius: Radius.sm, padding: Spacing.three, fontSize: FontSize.base }, actions: { flexDirection: 'row', justifyContent: 'flex-end', gap: Spacing.five, paddingTop: Spacing.three } });
