import React, { useMemo, useState } from 'react';
import { KeyboardAvoidingView, Modal, Platform, View, Text, TextInput, FlatList, TouchableOpacity, StyleSheet } from 'react-native';
import { useTheme } from '@/hooks/use-theme';
import { Spacing, Radius, FontSize, FontWeight } from '@/constants/theme';
import type { Supplier } from '@/utils/purchaseOrder';
export default function SupplierPickerSheet({ visible, suppliers, onClose, onPick }: { visible: boolean; suppliers: Supplier[]; onClose: () => void; onPick: (supplier: Supplier) => void }) {
  const theme = useTheme(); const [term, setTerm] = useState('');
  const results = useMemo(() => suppliers.filter((s) => s.supplier_name.toLowerCase().includes(term.trim().toLowerCase())), [suppliers, term]);
  return <Modal visible={visible} animationType="slide" transparent onRequestClose={onClose}><KeyboardAvoidingView style={styles.backdrop} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={[styles.backdropFill, { backgroundColor: theme.overlay }]}><View style={[styles.sheet, { backgroundColor: theme.surface }]}><View style={styles.head}><Text style={[styles.title, { color: theme.text }]}>Select supplier</Text><TouchableOpacity onPress={onClose} accessibilityLabel="Close supplier picker"><Text style={{ color: theme.primary }}>Done</Text></TouchableOpacity></View><TextInput value={term} onChangeText={setTerm} placeholder="Search suppliers" placeholderTextColor={theme.textMuted} autoFocus returnKeyType="search" style={[styles.input, { color: theme.text, backgroundColor: theme.surfaceMuted, borderColor: theme.border }]} /><FlatList data={results} keyExtractor={(item) => String(item.supplier_id)} keyboardShouldPersistTaps="handled" keyboardDismissMode="on-drag" renderItem={({ item }) => <TouchableOpacity onPress={() => { onPick(item); setTerm(''); }} style={[styles.item, { borderBottomColor: theme.border }]} accessibilityLabel={`Select ${item.supplier_name}`}><Text style={[styles.name, { color: theme.text }]}>{item.supplier_name}</Text>{item.contact_person ? <Text style={{ color: theme.textMuted, fontSize: FontSize.sm }}>{item.contact_person}</Text> : null}</TouchableOpacity>} ListEmptyComponent={<Text style={[styles.empty, { color: theme.textMuted }]}>No active suppliers found.</Text>} /></View></View></KeyboardAvoidingView></Modal>;
}
const styles = StyleSheet.create({ backdrop: { flex: 1 }, backdropFill: { flex: 1, justifyContent: 'flex-end' }, sheet: { maxHeight: '82%', borderTopLeftRadius: Radius.lg, borderTopRightRadius: Radius.lg, padding: Spacing.four, gap: Spacing.three }, head: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, title: { fontSize: FontSize.lg, fontWeight: FontWeight.bold }, input: { borderWidth: StyleSheet.hairlineWidth, borderRadius: Radius.md, padding: Spacing.three, fontSize: FontSize.base }, item: { paddingVertical: Spacing.three, gap: 2, borderBottomWidth: StyleSheet.hairlineWidth }, name: { fontSize: FontSize.base, fontWeight: FontWeight.semibold }, empty: { textAlign: 'center', padding: Spacing.five } });
