name: CI

on:
  push:
    branches: [ master ]
    paths:
      - 'packages/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'packages/**'
      - '.github/workflows/ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          # --- FIX: Point cache to the directories with package-lock.json ---
          cache-dependency-path: |
            packages/api/package-lock.json
            packages/web/package-lock.json
          
      - name: Install API dependencies
        run: npm install
        working-directory: packages/api

      - name: Install Web dependencies
        run: npm install
        working-directory: packages/web
          
      - name: Run API ESLint
        run: npm run lint
        working-directory: packages/api

      - name: Run Web ESLint
        run: npm run lint
        working-directory: packages/web
          
      - name: Run API tests
        env:
          NODE_ENV: test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
          POSTGRES_HOST: localhost
        run: npm test
        working-directory: packages/api
        
      - name: Run Web tests
        run: npm test
        working-directory: packages/web
          
      - name: Upload test coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            packages/api/coverage
            packages/web/coverage