name: Build and Push Docker Images

# This action runs on every push to the 'main' branch
on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    # The type of machine to run the job on
    runs-on: ubuntu-latest
    steps:
      # 1. Checks out your repository's code so the job can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Securely logs in to your Docker Hub account using the secrets you created
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Builds the Docker image for the backend and pushes it to Docker Hub
      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./packages/api
          push: true
          tags: kent1l/forson-backend:latest # Replace with your Docker Hub username

      # 4. Builds the Docker image for the frontend and pushes it to Docker Hub
      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./packages/web
          push: true
          tags: kent1l/forson-frontend:latest # Replace with your Docker Hub username